/*
 * defcon — src/landmask.js
 * 【自动生成，勿手改】由 tools/gen-landmask.py 从 Natural Earth 110m 陆地边界
 * （tools/ne_110m_land.geojson，公有领域）光栅化产出。
 *
 * 1° 分辨率海陆掩膜（1 bit / 格，1 = 陆地，0 = 海洋），行优先：
 *   第 0 行 = 北纬 +90 → 第 179 行 = 南纬 -90；第 0 列 = 西经 180 → 第 359 列 = 东经 180。
 *
 * 用途：布阵必须落在它该在的地方 —— 潜艇下不了陆地，发射井也修不到海里。
 *   旧版用「离最近城市 ≥ 9°」当作深海判据，城市只是陆地的稀疏采样点，
 *   撒哈拉 / 澳洲内陆 / 中亚离城市都很远但分明是陆地，潜艇照样爬上岸。
 * 体积：8100 字节位图 → base64 10800 字符，离线内联，不联网、不 fetch。
 */
(function (global) {
  'use strict';
  var DC = global.DC = global.DC || {};

  var W = 360, H = 180;
  var BITS = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADv//8AAP///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////D//////z/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/oP/5////////wAAAAANgAABoAAAAAAP4AAAAAAAAAAAAAAAAAAAAAAAAAAAf9/+Af///////AAAAB/7wAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAAAAAAEDzn3/4////////+AAAAAfgAAAAAAAAAAAAB8AAAAAAAAAAAAAAAAAAAAAAcIAAAH/AH///////+AAAAAHAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAB4DAM/f+AH///////4AAAAAAAAAAAAAB4AAAAB/+AAAAAAAAAAAAAAAAAAAAAH/4OT/8AAAP/////+AAAAAAAAAAAAD8AAAA////AAAA/gAAAAAAAAAAAAAAAAYAAAfIAAAH/////8AAAAAAAAAAAAPAAAAH///4AAAAAAAAAAAAAAAAAAAAP8AMeeMbgAAB/////8AAAAAAAAAAAA8AAAH/////+DwAHAAAAAAAAAAAAAAAfv7Y/Yf8wAAA/////QAAAAAAAAAAABwAHkH///////4APwAAAAAwAAAAAAAAPf/8GYf/8AABf////wAAAAAAAAAAADwAPt////////82//gAAAAAAAP+gAAAAAf/A+P//8AA////+AAAAAAAA/gAAAAAfn/////////////8AAAAAB///+D/3D//HPBwP+AAz////AAAAAAAf/8AAAAcPv/////////////+9H8wAP////////A4CPx4L8AAP///4AAAAAAB///4IBDf33/////////////////+AD////////+//f74Y/wAf//4AAAAAAAH///+Mf///n//////////////////8C/////////////gB/8Af//wAAIAAAAP//++H////f/////////////////v4f////////////8AD+YAP/4AAf8AAAA/8P+D///////////////////////AwFf///////////74//gAP/wAAP8AAAB/8/+f//////////////////////+ACA////////////BEA/wAH/gAAAAAAAH/z/////////////////////////+AAH///////////8AQAHAAD/AAAAAAAA//D///////////////////////3//AAH///////////4AAfgAAB/AAAAAAAA//D//////////////////////zv/AAAH/9z////////wAAf4AAAGAAAAAAAA//j9/////////////////////AfsAAAA/5AB///////wAAf4YAAAAAAAAAAA//gZ////////////////////OBwAAAAAF4AAf//////4AA/88AAAAAAAAAYA4+A///////////////////8AAHgAAAAABMAAB//////8AAP/+AAAAAAAAAcAC+Cf//////////////////wAAfwAAAAAEAAAA///////wAP/+AAAAAAAAAcAGeD///////////////////gAA/wAAAAAwAAAAf//////+Af//AAAAAAAAAOAF4D//////////////////+AAA/AAAAAAAAAAAP///////x///4AAAAAAADnAGBv//////////////////+AAA+AAAAAAAAAABn///////w///8AAAAAAAHHgf/////////////////////4AA+AAAAAAAAAAAD///////4///+AAAAAAAHPx///////////////////////AAYAAAAAAAAAAAB///////9///+AAAAAAAAPz//////////////////////7AAQAAAAAAAAAAAD///////////kAAAAAAAAYP//////////////////////5AAAAAAAAAAAAAAA3////////+AOAAAAAAAAA///////////////////////5gAAAAAAAAAAAAAAL////////7wPgAAAAAAAP///////////////////////6AAAAAAAAAAAAAAAP////////3wBwAAAAAAAD///////////////////////yAAAAAAAAAAAAAAAP/////////4AAAAAAAAAB/////vH/w//////////////iAAAAAAAAAAAAAAAH//////////AAAAAAAAAB//v//HP/A//////////////CAAAAAAAAAAAAAAAP////////+4AAAAAAAAAB//j/+CH+H/////////////+DAAAAAAAAAAAAAAAP////////wAAAAAAAAADx/xx/+AD/D/////////////4DwAAAAAAAAAAAAAAP////////wAAAAAAAAAH/8E4f8AA/B////////////+ANAAAAAAAAAAAAAAAP////////wAAAAAAAAAD/4EeP+Pg/gf///////////8AEAAAAAAAAAAAAAAAP///////8AAAAAAAAAAD/gEHvh///5///////////v8AMAAAAAAAAAAAAAAAH///////8AAAAAAAAAAH/AEDHH///w///////////IwAEAAAAAAAAAAAAAAAH///////4AAAAAAAAAAH/AACHH///g//////////8B4AMAAAAAAAAAAAAAAAD///////wAAAAAAAAAAD+AAcDD///w//////////+QcAYAAAAAAAAAAAAAAAB///////4AAAAAAAAAAAwP+ABAu//////////////gcB4AAAAAAAAAAAAAAAB///////4AAAAAAAAAAAx/+AAgA//////////////AcP4AAAAAAAAAAAAAAAA///////gAAAAAAAAAAA//+AAAA//////////////AQ7AAAAAAAAAAAAAAAAAH/////+AAAAAAAAAAAD//+AAAA//////////////gBYAAAAAAAAAAAAAAAAAH/////8AAAAAAAAAAAH///4HAB//////////////wBAAAAAAAAAAAAAAAAAADf////4AAAAAAAAAAAH///8P4R//////////////wBAAAAAAAAAAAAAAAAAADf////4AAAAAAAAAAAH////v////////////////wAAAAAAAAAAAAAAAAAAABP//xgYAAAAAAAAAAAH/////////n///////////4AAAAAAAAAAAAAAAAAAAAn//AAMAAAAAAAAAAAf/////////j///////////wAAAAAAAAAAAAAAAAAAAAz/+AAMAAAAAAAAAAB///////8//x///////////gAAAAAAAAAAAAAAAAAAAAZ/+AAMAAAAAAAAAAB///////8f/4D//////////gAAAAAAAAAAAAAAAAAAAAJ/+AAEAAAAAAAAAAD///////+f/8I//////////AAAAAAAAAAAAAAAAAAAAAEf+AAAgAAAAAAAAAH////////P/8YAP///////+QAAAAAAAAAAAAAAAAAAAACP+AAAAAAAAAAAAAP////////H//+AH///////8QAAAAAAAAAAAAAAAAAAAAAH+AAuAAAAAAAAAAP////////j///AD///v///gQAAAAAAAAAAAAAAAAAAAAAH+AAAwAAAAAAAAAf////////z///AD//8H//MAAAAAAAAAAAAAAAAAAAAAAAH+A4AcAAAAAAAAAP////////z//+AAf/4H/+IAAAAAAAAAAAAAAAQAAAAAAAH/A4AA4AAAAAAAAP////////x//8AAf/wD/8YAAAAAAAAAAAAAAAAAAAAAAAB/z4AC9AAAAAAAAP////////w//4AAf/gB/+YAQAAAAAAAAAAAAAAAAAAAAAAf/wAAAAAAAAAAAP////////4f/wAAP+AB/+AAYAAAAAAAAAAAAAAAAAAAAAAD/wAAAAAAAAAAAP////////8f+AAAP+ABv/AAYAAAAAAAAAAAAAAAAAAAAAAAH/gAAAAAAAAAAP////////8f8AAAP4AAP/gAwAAAAAAAAAAAAAAAAAAAAAAAD/gAAAAAAAAAAf/////////fwAAAH4AAP/wAQAAAAAAAAAAAAAAAAAAAAAAAAfgAAAAAAAAAAP/////////vAAAAH4AAH/wAUAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAP/////////wAAAAH4AAG/wABAAAAAAAAAAAAAAAAAAAAAAAADgAoAAAAAAAAH/////////wMAAADwAAEfgAFAAAAAAAAAAAAAAAAAAAAAAAABgH/NAAAAAAAD//////////4AAABwAAEHAAPAAAAAAAAAAAAAAAAAAAAAAAAAwH/+AAAAAAAB//////////4AAABwAAEGAAEAAAAAAAAAAAAAAAAAAAAAAAAAe///gAAAAAAB//////////4AAABsAAGAAABgAAAAAAAAAAAAAAAAAAAAAAAAA///wAAAAAAA//////////wAAAAMAACAAAFgAAAAAAAAAAAAAAAAAAAAAAAAAf//4AAAAAAAf/////////wAAAAEAABAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAf///gAAAAAAH/A///////gAAAAAAABgAOAAAAAAAAAAAAAAAAAAAAAAAAAAAf///4AAAAAACAA3//////AAAAAAAA5wAeAAAAAAAAAAAAAAAAAAAAAAAAAAAf///4AAAAAAAAAD//////AAAAAAAAcwA8AAAAAAAAAAAAAAAAAAAAAAAAAAA////8AAAAAAAAAD/////+AAAAAAAAOwD8AAAAAAAAAAAAAAAAAAAAAAAAAAA////+AAAAAAAAAD/////4AAAAAAAAHoP+BIAAAAAAAAAAAAAAAAAAAAAAAAD////8AAAAAAAAAD/////wAAAAAAAADwf8eIAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAD/////gAAAAAAAADwP8gAAAAAAAAAAAAAAAAAAAAAAAAAD/////4AAAAAAAAD/////AAAAAAAAAB4P44A4AAAAAAAAAAAAAAAAAAAAAAAB/////9AAAAAAAAD////+AAAAAAAAAA8H5wAZ4AAAAAAAAAAAAAAAAAAAAAAD//////8AAAAAAAB////8AAAAAAAAAAeAY4Qf/AAAAAAAAAAAAAAAAAAAAAAH//////+AAAAAAAA////8AAAAAAAAAAMAAsAD/wMAAAAAAAAAAAAAAAAAAAAH///////gAAAAAAAf///4AAAAAAAAAAEAAgAA/4wAAAAAAAAAAAAAAAAAAAAD///////wAAAAAAAf///4AAAAAAAAAADgAAAAf8AAAAAAAAAAAAAAAAAAAAAB///////wAAAAAAAf///8AAAAAAAAAAA+AAAAf8AAAAAAAAAAAAAAAAAAAAAA///////gAAAAAAAP///8AAAAAAAAAAAAy4gAHGABAAAAAAAAAAAAAAAAAAAA///////gAAAAAAAP///8AAAAAAAAAAAAAiAAADACAAAAAAAAAAAAAAAAAAAA///////AAAAAAAAP///+AAAAAAAAAAAAAAAAAAgAgAAAAAAAAAAAAAAAAAAAf/////+AAAAAAAAP///+AAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAP/////+AAAAAAAAP///+AQAAAAAAAAAAAAB+DAAAAAAAAAAAAAAAAAAAAAAAP/////8AAAAAAAAf///+AYAAAAAAAAAAAAB+DAAAAAAAAAAAAAAAAAAAAAAAP/////8AAAAAAAAf///+A4AAAAAAAAAAAA78DAAAAAAAAAAAAAAAAAAAAAAAD/////8AAAAAAAA////+B4AAAAAAAAAAAB/+DwAABAAgAAAAAAAAAAAAAAAAB/////4AAAAAAAA////8HwAAAAAAAAAAAH//DwAAAABAAAAAAAAAAAAAAAAAAf////4AAAAAAAA////wPwAAAAAAAAAAAH//34AAAACAAAAAAAAAAAAAAAAAAP////4AAAAAAAAf///gHwAAAAAAAAAAAP///4AAAAAAAAAAAAAAAAAAAAAAAP////4AAAAAAAAf///AHgAAAAAAAAAAAP///8AAAAAAAAAAAAAAAAAAAAAAAP////wAAAAAAAAP//+AHgAAAAAAAAAAD////+AAEAAAAAAAAAAAAAAAAAAAAP////wAAAAAAAAP///APgAAAAAAAAAAP/////AACAAAAAAAAAAAAAAAAAAAAP////gAAAAAAAAH///APAAAAAAAAAAA//////gAAAAAAAAAAAAAAAAAAAAAAP///8AAAAAAAAAH///APAAAAAAAAAAA//////gAAAAAAAAAAAAAAAAAAAAAAP///gAAAAAAAAAH//+APAAAAAAAAAAA//////4AAAAAAAAAAAAAAAAAAAAAAP///AAAAAAAAAAH//4AAAAAAAAAAAAAf/////4AAAAAAAAAAAAAAAAAAAAAAP///AAAAAAAAAAD//4AAAAAAAAAAAAA//////8AAAAAAAAAAAAAAAAAAAAAAP///AAAAAAAAAAD//4AAAAAAAAAAAAAf/////8AAAAAAAAAAAAAAAAAAAAAAf///AAAAAAAAAAB//4AAAAAAAAAAAAAf/////8AAAAAAAAAAAAAAAAAAAAAAf//+AAAAAAAAAAB//wAAAAAAAAAAAAAP/////8AAAAAAAAAAAAAAAAAAAAAAf//8AAAAAAAAAAA//gAAAAAAAAAAAAAP/////8AAAAAAAAAAAAAAAAAAAAAAf//4AAAAAAAAAAAf/AAAAAAAAAAAAAAP/////4AAAAAAAAAAAAAAAAAAAAAAf//wAAAAAAAAAAAf+AAAAAAAAAAAAAAP/AH//4AAAAAAAAAAAAAAAAAAAAAAf//gAAAAAAAAAAAf4AAAAAAAAAAAAAAP+AH//wAAAAAAAAAAAAAAAAAAAAAA//zAAAAAAAAAAAAIAAAAAAAAAAAAAAAOAAC//gAABAAAAAAAAAAAAAAAAAAA//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/gAAAgAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/gAAAAAAAAAAAAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/AAAAQAAAAAAAAAAAAAAAAAB//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMAAAAeAAAAAAAAAAAAAAAAAB/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAB/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAB/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAAADgAAAAAAAAAAAAAAAAAC/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAADAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAOAAAAAAAAAAAAAAAAAAD/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAH+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAD/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+AAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8A4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAD8AAAACAA8HwAB+AAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAf/iAAD//////////4AAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAf///8Af///////////AAAAAAAAAAAAAAAAAAAAAAAb8AAAAAAAAAAAAAAAHz////8A/////////////4AAAAAAAAAAAAAAAAAAAAAf8AAAAAAAAAAAef+f//////wP//////////////AAAAAAAAAAAAAAAAAAAAD9+AAAAAAAAN/f//////////4////////////////4AAAAAAAAAAAAAAAAAAAB+AAAAAAAA//////////////////////////////4AAAAAAAAAACAAB+f/Dh//AAAAAAAP//////////////////////////////wAAAAAAAAP/s/wAP/////8AAAAAAAH/////////////////////////////8AAAAAAAD/////////////gAAAAAAB//////////////////////////////4AAAAAAAD////////////wAAAAAAH///////////////////////////////wAAAAAD/////////////8AAAAAAB////////////////////////////////4AAAABw/////////////gAAAB+Af////////////////////////////////+AAAAAYAP///////////wAAAD+AAf///////////////////////////////AAAAAAAAD////////////Afgf4AAf//////////////////////////////+AAAAAAAf//////////////gAAAf/////////////////////////////////AAAAAAAD///////////////g////////////////////////////////////4AAAAAAH/////////////////////////////////////////////////////wAf/gAAH/////////////////////////////////////////////////////+/////n//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////';

  /* base64 → 字节数组。手写 64 字符查表：不碰 atob（Node 无头环境没有它），
   * 也不碰 Buffer（浏览器端没有它）—— 逻辑层与无头测试要共用同一份代码。 */
  var B64 = (function () {
    var A = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    var t = {};
    for (var i = 0; i < 64; i++) t[A.charAt(i)] = i;
    return t;
  })();
  var bytes = (function (s) {
    var n = s.length, out = [], buf = 0, bits = 0;
    for (var i = 0; i < n; i++) {
      buf = (buf << 6) | B64[s.charAt(i)];
      bits += 6;
      if (bits >= 8) { bits -= 8; out.push((buf >> bits) & 0xFF); }
    }
    return out;
  })(BITS);

  function cellAt(lat, lon) {
    var ix = Math.floor(((lon + 180) % 360) * W / 360);
    var iy = Math.floor((90 - lat) * H / 180);
    if (ix < 0) ix = 0; if (ix >= W) ix = W - 1;
    if (iy < 0) iy = 0; if (iy >= H) iy = H - 1;
    return iy * W + ix;
  }

  function bit(n) {
    return (bytes[n >> 3] >> (7 - (n & 7))) & 1;
  }

  /* 该点是陆地吗（只看自己这一格）。掩膜给布阵"挑地方"用，单格精度足够：1° ≈ 111 km。 */
  function isLand(lat, lon) {
    return bit(cellAt(lat, lon)) === 1;
  }

  /* 该点及四邻（radiusDeg）都是陆地吗 —— 内陆判据。
   * 发射井要修在纵深里，贴在海岸线上视觉上像"泡在水边"，也容易被一发带走。 */
  function isInland(lat, lon, radiusDeg) {
    var d = radiusDeg || 1;
    return isLand(lat, lon) &&
           isLand(lat + d, lon) && isLand(lat - d, lon) &&
           isLand(lat, lon + d) && isLand(lat, lon - d);
  }

  /* 该点及四邻（radiusDeg）都是水吗 —— 深海判据。
   * 潜艇不能贴着海岸线蹲：既不符合"藏在深海里"的叙事，也会被玩家一眼看穿是贴图错位。 */
  function isDeepWater(lat, lon, radiusDeg) {
    var d = radiusDeg || 2;
    return !isLand(lat, lon) &&
           !isLand(lat + d, lon) && !isLand(lat - d, lon) &&
           !isLand(lat, lon + d) && !isLand(lat, lon - d);
  }

  DC.land = {
    W: W, H: H,
    isLand: isLand,
    isWater: function (lat, lon) { return !isLand(lat, lon); },
    isInland: isInland,
    isDeepWater: isDeepWater
  };

})(typeof window !== 'undefined' ? window : globalThis);
