/* 人类科技树 · 数据真源（经典脚本，ES2017 基线，无模块 / 无内联事件 / 无求值）
 *
 * 参照文明系列（Civilization）的科技树形态：把人类技术按时代分层排列，
 * 每一项科技列出它的「前置科技」（roots），页面据此画出前置连线。
 *
 * 数据是唯一真源：
 *   ERAS      —— 时代（10 个，按时间从早到晚；accent 为该时代主题色）
 *   TECHS     —— 科技条目（era 指向 ERAS.key；roots 指向同代或更早时代的 id）
 *   IMG_STYLE —— 配图提示词的统一风格前缀
 *
 * 配图：条目图 ./assets/img/<id>.<ext>，时代封面 ./assets/img/cover-<eraKey>.<ext>；
 *       文件缺失时页面自动显示占位块（写明期望文件名），补图不需要改代码。
 *       提示词清单由 _dev/gen_image_prompts.py 从本文件派生到 _dev/IMAGE_PROMPTS.md。
 *
 * 数据约定（_dev/check_data.py 会逐条校验）：
 *   - roots 里的 id 必须存在，且所在时代不晚于本条目所在时代；
 *   - 前置关系整体必须无环（DAG）；
 *   - 每个时代至少有一个「根节点」（roots 为空）或上溯到根节点的连接。
 */

/* ============================ 时代 ============================ */
var ERAS = [
  {key:"prehistoric", zh:"远古时代", en:"Prehistoric", span:"约 300 万年前 — 公元前 3500 年",
   note:"石器、用火与语言：技术刚刚开始能被一代代累积下来。",
   accent:"#8a6a4c", soft:"#f5efe7", icon:"fire"},
  {key:"bronze", zh:"早期文明", en:"Bronze Age", span:"公元前 3500 — 前 1200 年",
   note:"农业、陶器、文字与青铜：定居社会长出了第一批专职技术。",
   accent:"#b07d24", soft:"#fbf3e2", icon:"pot"},
  {key:"classical", zh:"古典时代", en:"Classical Age", span:"公元前 1200 — 公元 500 年",
   note:"铁器、数学、天文与哲学：知识第一次被系统地写下来。",
   accent:"#2f6f7f", soft:"#e8f3f5", icon:"column"},
  {key:"medieval", zh:"中世纪", en:"Medieval", span:"500 — 1450 年",
   note:"纸、印刷、火药、指南针与机械钟：为远航与革命备好了工具。",
   accent:"#4a6b52", soft:"#eaf2ec", icon:"castle"},
  {key:"renaissance", zh:"大航海与科学革命", en:"Discovery & Science", span:"1450 — 1700 年",
   note:"远洋航线、日心说、微积分与经典力学：人类开始用观测和计算解释世界。",
   accent:"#6d4f9a", soft:"#f1ecfa", icon:"sextant"},
  {key:"industrial", zh:"工业时代", en:"Industrial", span:"1700 — 1870 年",
   note:"蒸汽、纺织机械、钢铁、铁路、近代化学与演化论。",
   accent:"#8c4a3f", soft:"#fbeeeb", icon:"gear"},
  {key:"electric", zh:"电气与原子时代", en:"Electric & Atomic", span:"1870 — 1950 年",
   note:"电网、内燃机、航空、无线电、现代物理与核裂变。",
   accent:"#1d6fe0", soft:"#e9f1fe", icon:"bolt"},
  {key:"information", zh:"信息时代", en:"Information", span:"1950 — 2000 年",
   note:"计算机、晶体管、航天、互联网与分子生物学。",
   accent:"#0891b2", soft:"#e6f7fb", icon:"chip"},
  {key:"digital", zh:"数字与智能时代", en:"Digital & Intelligent", span:"2000 年 — 今",
   note:"移动互联网、云计算、深度学习、基因编辑与新能源。",
   accent:"#db2777", soft:"#fdeaf3", icon:"phone"},
  {key:"future", zh:"近未来", en:"Future", span:"2020 年代 — 未来",
   note:"通用人工智能、核聚变、脑机接口、合成生物学与太空工业：仍在路上的分支。",
   accent:"#334155", soft:"#eef1f5", icon:"stars"}
];

/* 配图统一风格：所有条目图 / 时代封面图共用同一套渲染规格，保证整册视觉一致。
   写法要点：
   1) 明确「两种模式」——实拍器物（影棚光）或极简 3D 概念图，其余全靠 subject 描述；
   2) 构图用量化短句（主体只占画面中间一半高度、上下留大空白），压住模型「越大越好看」
      的默认倾向，否则主体会被卡片裁掉；
   3) 负面项集中放最后。只禁「可读的现代文字」，因为文字、数学、货币、医学等条目
      本身画的就是带铭文的器物，难看的涂鸦式标记反而更失真。
   图片生成 agent 请把本串 + 条目的 subject 拼接后使用。 */
var IMG_STYLE = "Clean editorial encyclopedia image of a single subject, either a photorealistic museum artifact photograph or a clean minimalist 3D conceptual rendering, clear three-quarter or side view, soft even studio lighting, seamless plain light-gray background, subtle soft contact shadow, the subject is fully inside the frame and horizontally centered, occupying only the middle half of the frame height, wide empty background above and below, muted restrained color palette, no readable modern text, no letters, no numerals, no logos, no brand marks, no watermarks, landscape 16:9";

/* ============================ 科技条目 ============================ */
/* era 为所属时代 key；roots 为前置科技 id（可为空数组，表示该时代的起点科技）；
   year 为该技术出现时间的取整表述；specs 为关键参数；feats 为亮点；
   subject 为生图用主体描述（英文，不含风格串），只写主体本身、不写画面风格。 */
var TECHS = [

  /* ==================== 远古时代 ==================== */
  {id:"stone-tools", era:"prehistoric", name:"石器制作", en:"Stone Tools", year:"约 330 万年前", roots:[],
   tag:"人类造出的第一件工具，也是全部技术的共同祖先",
   intro:"把石头敲打出锋利的边缘，是最早的「制造」行为。石器让人能切割、刮削、砍砸，也让此后所有技术有了同一个出发点：用工具去改造环境。",
   specs:[["出现时间","约 330 万年前"],["材料","燧石、石英、黑曜石"],["工艺","打制 → 磨制（约 1 万年前）"],["用途","切割、刮削、狩猎、加工木器"]],
   feats:["打制石器延续数百万年，是已知最长的技术传统","磨制石器与新石器时代、农业几乎同时到来","石料的长距离交换，说明早期人类已有跨区域物资网络"],
   subject:"a neat little collection of prehistoric knapped flint tools — a teardrop hand axe, a scraper and three blade flakes — arranged on a plain neutral surface, chipped stone texture, museum artifact photograph"},
  {id:"fire", era:"prehistoric", name:"用火", en:"Control of Fire", year:"约 100 万年前", roots:[],
   tag:"第一项被驯服的自然力",
   intro:"火带来取暖、照明、驱兽与熟食。熟食缩短了咀嚼与消化时间，改变了人类的体质，而围火而居也成了社会生活最早的舞台。",
   specs:[["出现时间","约 100 万年前（普遍用火约 40 万年前）"],["取火方式","摩擦、燧石打火"],["主要用途","烹饪、取暖、照明、烧制"],["后续影响","陶器、冶金、蒸汽、内燃机的共同前提"]],
   feats:["熟食被认为与人类脑容量增长、牙齿变小直接相关","火让人第一次能在寒冷地区与夜间持续活动","一切高温工艺——陶、玻璃、金属——都从控制火开始"],
   subject:"a controlled campfire with orange flames and glowing embers inside a small ring of plain stones, a few thin sparks rising, dark neutral background, no people, no text"},
  {id:"language", era:"prehistoric", name:"语言", en:"Spoken Language", year:"约 10 万年前", roots:[],
   tag:"让知识可以在一代代之间累积",
   intro:"语言把经验从一个人的脑子里搬进群体的记忆。有了语言，技术第一次能够被讲述、纠正与叠加，人类由此走出了「每一代都从头再来」的循环。",
   specs:[["出现时间","约 10 万年前（或更早）"],["形式","语音符号系统"],["关键作用","知识传递、协作、规划"],["后续影响","文字（约公元前 3200 年）"]],
   feats:["「累积文化」——技术逐代叠加而不是重置——是人类的关键差异","语言让大规模协作与分工第一次成为可能","口头传承了数万年的知识，最终被文字固定下来"],
   subject:"an abstract minimalist 3D rendering of a glowing network of thin luminous lines joining small bright nodes inside a soft rounded cloud shape, deep blue-gray palette, conceptual visualization, no text"},
  {id:"hunting", era:"prehistoric", name:"狩猎与采集", en:"Hunting & Gathering", year:"约 30 万年前", roots:["stone-tools"],
   tag:"人类维持最久的一种经济形态",
   intro:"用石器与协作围猎、采集果实与根茎，是人类维持了数十万年之久的谋生方式。它要求对季节、动植物与地形的细致观察，是最早的博物学。",
   specs:[["出现时间","约 30 万年前"],["工具","石矛、刮削器、投掷器、陷阱"],["食物来源","猎物、果实、根茎、贝类"],["组织形式","小群体协作"]],
   feats:["对动植物的长期观察积累了最早的生物学与季节知识","长距离追踪与协作围猎，需要复杂的社会组织","采集经济比农业更稳定，却养不活更多人口"],
   subject:"a museum-style diorama of three small prehistoric hunter figures in plain hide clothing, two holding simple stone-tipped wooden spears, standing on a plain light-gray surface, three-quarter view, no text"},
  {id:"clothing", era:"prehistoric", name:"衣物与缝纫", en:"Clothing & Sewing", year:"约 17 万年前", roots:["hunting"],
   tag:"让人类走出热带",
   intro:"把兽皮刮净、用骨针与筋线缝成衣服，人类第一次把体温与环境隔开。衣物让迁徙进入寒带成为可能，也催生了最早的手工行业。",
   specs:[["出现时间","约 17 万年前（骨针约 4 万年前）"],["材料","兽皮、毛皮、植物纤维"],["工具","刮刀、骨针、锥子"],["用途","御寒、防护、身份标识"]],
   feats:["与用火一起，让人类在冰期扩展到欧亚大陆北部","骨针是精密工具的早期代表，需要极高的手工水平","纺织技术从缝制兽皮一路走到编织与织机"],
   subject:"a neatly folded pile of pale hide and fur garments with visible hand stitching, beside two bone needles and a coiled sinew thread, on a plain neutral surface, museum artifact photograph, no text"},
  {id:"canoe", era:"prehistoric", name:"独木舟", en:"Watercraft", year:"约 5 万年前", roots:["stone-tools","fire"],
   tag:"人类第一次跨越水面",
   intro:"用火与石器把整根树干掏空，就得到最古老的船。独木舟让人越过海峡、抵达澳洲与太平洋岛屿，也第一次把运输从陆地搬到水上。",
   specs:[["出现时间","约 5 万年前（跨海迁徙约 6 万年前）"],["材料","整木、树皮、兽皮"],["动力","人力划桨、篙、风帆"],["用途","渔猎、渡水、迁徙、贸易"]],
   feats:["抵达澳大利亚需要跨海航行，是已知最早的远洋迁徙证据","与风帆结合后，成为数万年间水上运输的主角","是帆船、轮船等一切水上交通的共同起点"],
   subject:"a simple dugout canoe carved from a single log with a wooden paddle resting across the gunwales, weathered dark wood with visible adze marks, three-quarter view, plain neutral background"},

  /* ==================== 早期文明 ==================== */
  {id:"pottery", era:"bronze", name:"陶器", en:"Pottery", year:"约公元前 6000 年", roots:["fire"],
   tag:"人类造出的第一种人造材料",
   intro:"把黏土塑形再用火烧结，人类第一次造出自然界里没有的材料。陶器让粮食可以储存与烹煮，也带来了窑炉——此后所有高温工艺的母体。",
   specs:[["出现时间","约公元前 2 万年（普及约前 6000 年）"],["材料","黏土经高温烧结"],["关键工艺","塑形、窑烧、轮制"],["用途","储粮、炊煮、砖瓦、礼器"]],
   feats:["陶轮是最早的旋转机械，与后来的轮子同源","高温窑是青铜、玻璃、陶瓷的共同前置","陶片是考古学判断年代与文化最重要的依据"],
   subject:"a group of unglazed earthenware vessels — two round jars, a wide bowl and a small cup with simple incised patterns — arranged on a plain neutral surface, warm terracotta color, museum artifact photograph"},
  {id:"agriculture", era:"bronze", name:"农业", en:"Agriculture", year:"约公元前 9500 年", roots:["hunting"],
   tag:"人类第一次主动改造环境来生产食物",
   intro:"选种、播种、灌溉与收获，把野草变成小麦，把野猪变成家猪。农业让同样的土地能养活更多人，也让村落、剩余产品与国家成为可能。",
   specs:[["出现时间","约公元前 9500 年（西亚新月沃地）"],["作物","小麦、大麦、水稻、粟、玉米"],["关键技术","选育、播种、灌溉、轮作"],["影响","定居、人口增长、国家起源"]],
   feats:["定居与剩余粮食直接催生了城市、文字与阶级","作物驯化改变了植物的基因，也改变了人类的作息","农业是水利、货币、仓储等一系列技术的动因"],
   subject:"a compact museum-style diorama of a small hand-tilled field of ripe wheat with a simple wooden digging stick and two harvested bundles lying on the soil, plain light-gray surroundings, no people, no text"},
  {id:"animal-husbandry", era:"bronze", name:"畜牧", en:"Animal Husbandry", year:"约公元前 8500 年", roots:["hunting"],
   tag:"把猎物变成伙伴与动力",
   intro:"驯化山羊、绵羊、牛、马与骆驼，人类获得了稳定的肉、奶、毛皮与畜力。牲畜从此既是食物储备，也是人类最古老的「动力机械」。",
   specs:[["出现时间","约公元前 8500 年"],["主要畜种","羊、牛、猪、马、骆驼、鸡"],["产物","肉、奶、毛皮、肥料、畜力"],["影响","耕作、运输、贸易"]],
   feats:["畜力把可耕作面积与运输半径成倍放大","乳制品让部分人群演化出成年后消化乳糖的能力","与耕作结合，形成持续数千年的农业体系"],
   subject:"a small group of domesticated farm animals — two goats, a sheep and a brown cow — standing together on a plain light-gray surface with a simple wooden fence behind them, museum-style diorama, no people, no text"},
  {id:"weaving", era:"bronze", name:"纺织", en:"Weaving & Textiles", year:"约公元前 6000 年", roots:["clothing","agriculture"],
   tag:"把纤维变成布料",
   intro:"把亚麻、棉花、羊毛搓成线、再经纬交织成布，人类第一次批量「制造」出柔软的材料。纺织从家庭手工一路成长为最早的机械化产业。",
   specs:[["出现时间","约公元前 6000 年"],["原料","亚麻、棉、羊毛、丝"],["关键工具","纺锤、纺车、织机"],["用途","衣着、帐幕、帆、绳索、包装"]],
   feats:["纺锤与织机是人类最早的成套机械","丝绸（约公元前 2700 年）长期是中国最重要的出口商品","两千年后，正是纺织机械点燃了工业革命"],
   subject:"a simple wooden frame loom with undyed linen fabric partially woven on it, a wooden shuttle and two spools of thread lying beside it, plain neutral background, no people, no text"},
  {id:"wheel", era:"bronze", name:"轮子", en:"The Wheel", year:"约公元前 3500 年", roots:["pottery"],
   tag:"把滑动摩擦换成滚动摩擦",
   intro:"轮子把物体的移动方式从「拖」变成「滚」，让同样的力气能挪动重得多的东西。它从陶轮演化而来，随后进入车辆、磨坊与机械，成为几乎所有机器的零件。",
   specs:[["出现时间","约公元前 3500 年（美索不达米亚）"],["结构","轮、轴、轴承、车架"],["材料","木 → 铁箍 → 橡胶与合金"],["用途","运输、制陶、磨粉、传动"]],
   feats:["轮轴让畜力运输的效率提高数倍","辐条轮大幅减重，马车与战车由此普及","齿轮、滑轮、飞轮都是轮轴原理的延伸"],
   subject:"an ancient wooden cart wheel with thick spokes and a solid wooden hub standing upright, weathered wood with a visible iron rim, plain neutral background, museum artifact photograph"},
  {id:"sailing", era:"bronze", name:"风帆", en:"Sailing", year:"约公元前 3500 年", roots:["canoe","weaving"],
   tag:"第一台用自然力替代人力的「发动机」",
   intro:"把织好的布张挂在桅杆上，风就成了免费的推力。风帆让船能载着成吨的货物跨越海洋，把地中海、印度洋与后来的大西洋连成一张贸易网。",
   specs:[["出现时间","约公元前 3500 年（埃及方帆）"],["形式","方帆 → 三角帆 → 纵帆"],["动力","风力，辅以划桨"],["用途","贸易、运输、探索、渔业"]],
   feats:["三角帆与纵帆让船能逆风蛇形前进，远洋航行成为可能","风帆是第一个规模化利用自然能量的技术","从木帆船到钢铁帆船，帆作为动力延续了五千多年"],
   subject:"an ancient wooden sailing boat with a single square woven sail stretched on a short mast, simple rope rigging, small hull, plain neutral background, three-quarter view, no water surface"},
  {id:"writing", era:"bronze", name:"文字", en:"Writing", year:"约公元前 3200 年", roots:["agriculture"],
   tag:"让信息脱离人脑与口耳",
   intro:"从记账的符号到完整的文字系统，人类第一次能把说过的话原样存下来。文字让法律、历史、科学与行政都得以超越一代人的寿命。",
   specs:[["出现时间","约公元前 3200 年（苏美尔楔形文字）"],["早期形态","楔形文字、圣书体、甲骨文"],["载体","泥板、甲骨、竹简、莎草纸"],["作用","记账、法令、历史、知识"]],
   feats:["文字起源于仓储与税收的记账需求","使知识可以跨代、跨地域累积，是科学的前提","从泥板到竹简再到纸，载体决定了知识的传播范围"],
   subject:"an ancient clay tablet with neat rows of pressed wedge-shaped marks, a small bone stylus lying beside it, warm earth tones, plain neutral background, museum artifact photograph"},
  {id:"bronze", era:"bronze", name:"青铜冶炼", en:"Bronze Working", year:"约公元前 3300 年", roots:["pottery"],
   tag:"人类第一个冶金时代",
   intro:"把铜矿石与锡一起加热到一千度以上，得到比石头更硬、还能重铸的青铜。金属让工具、武器与礼器第一次可以被复制，也催生了矿冶与远途贸易。",
   specs:[["出现时间","约公元前 3300 年"],["材料","铜锡合金（约九比一）"],["关键工艺","采矿、冶炼、范铸、锻造"],["用途","工具、武器、礼器、货币"]],
   feats:["高温窑炉与鼓风技术是青铜冶铸的共同前提","合金比纯金属更硬，是材料设计思想的起点","铸造出的大型青铜礼器，至今仍是工艺高峰"],
   subject:"an ancient bronze ritual vessel with a rounded body, two upright handles and intricate cast patterns, greenish patina, standing on a plain neutral surface, museum artifact photograph"},

  /* ==================== 古典时代 ==================== */
  {id:"iron", era:"classical", name:"铁器", en:"Iron Working", year:"约公元前 1200 年", roots:["bronze"],
   tag:"让金属工具走进普通人的生活",
   intro:"铁矿石分布极广、冶炼温度更高，一旦掌握，金属工具就迅速普及到农耕与日常生活。铁犁、铁刀与铁钉支撑了此后两千多年的农业与建筑。",
   specs:[["出现时间","约公元前 1200 年（普及约前 500 年）"],["材料","铁（熟铁、渗碳钢）"],["关键工艺","块炼、渗碳、淬火、鼓风炉"],["用途","农具、兵器、建筑、工具"]],
   feats:["铁矿远比铜锡丰富，使金属器具第一次走向大众","中国战国时期大规模使用铁农具，粮食产量随之跃升","渗碳与淬火，是钢铁技术的雏形"],
   subject:"a hand-forged iron axe head and several iron nails lying beside a blacksmith's hammer on a plain neutral surface, dark rough metal texture, museum artifact photograph"},
  {id:"mathematics", era:"classical", name:"数学", en:"Mathematics", year:"约公元前 1800 年", roots:["writing"],
   tag:"抽象符号第一次被用来描述规律",
   intro:"从计数与土地丈量出发，数学发展出算术、几何与证明。《九章算术》《几何原本》等著作，把具体问题的解法提炼成可以传承的通用方法。",
   specs:[["出现时间","约公元前 1800 年（古巴比伦泥板）"],["早期内容","算术、几何、代数、证明"],["代表著作","《九章算术》《几何原本》"],["作用","工程、天文、贸易、税收"]],
   feats:["十进制与位值制来自中国与印度，今天通行全世界","欧几里得把「证明」确立为数学与科学的方法","数学是所有精确科学的语言与地基"],
   subject:"an ancient clay tablet covered with neat rows of geometric diagrams and simple tally marks, a bundle of thin bone counting rods lying beside it, plain neutral background, museum artifact photograph"},
  {id:"currency", era:"classical", name:"货币", en:"Currency", year:"约公元前 600 年", roots:["writing","bronze"],
   tag:"把价值变成可以携带与交换的东西",
   intro:"从称重金属到铸成定值的钱币，货币让交易摆脱了「以物易物」的双向巧合。价格、借贷、税收与工资随之出现，市场第一次有了统一的尺度。",
   specs:[["出现时间","约公元前 600 年（吕底亚铸币）"],["形态","金属称量 → 铸币 → 纸币 → 电子支付"],["关键属性","可分割、可储存、被公认"],["作用","交易、税收、借贷、记账"]],
   feats:["中国宋代交子是世界最早的纸币","货币把信用变成制度，是金融体系的起点","从贝壳到账本，形态一直在变，本质始终是共同的信任"],
   subject:"a small pile of ancient round bronze coins with square holes in the center, a few stacked and several scattered, dark green patina, plain neutral background, top-down macro photograph"},
  {id:"astronomy", era:"classical", name:"天文与历法", en:"Astronomy & Calendar", year:"约公元前 2000 年", roots:["writing","mathematics"],
   tag:"把天空的规律变成可以预测的时间",
   intro:"观测日影、月相与星象，人类第一次能预测季节与洪水。历法让播种、祭祀与税收有了统一的时间表，天文学也成为最早的精密科学。",
   specs:[["出现时间","约公元前 2000 年（系统性天象记录）"],["关键内容","日月运行、星座、节气、历法"],["工具","圭表、浑仪、观星台"],["作用","农时、祭祀、航海、导航"]],
   feats:["中国自公元前 613 年起连续记录哈雷彗星，是世界上最早最长的天象记录之一","历法精度长期是衡量文明水平的指标","天文学是数学与观测结合的第一次大规模实践"],
   subject:"an ancient bronze armillary sphere made of several intersecting engraved rings, dark green patina, standing on a plain neutral surface, museum artifact photograph, no text"},
  {id:"irrigation", era:"classical", name:"水利与灌溉", en:"Hydraulics", year:"约公元前 3000 年", roots:["agriculture","bronze"],
   tag:"把河流变成可以调度的资源",
   intro:"修渠、筑堤、挖井、造水车，人类第一次大规模改造水系。灌溉让旱季也能耕种，水利工程也催生了最早的组织化劳动力与国家治理。",
   specs:[["出现时间","约公元前 3000 年"],["关键技术","渠道、堤坝、水库、坎儿井、水车"],["材料与工具","夯土、石砌、青铜工具"],["作用","灌溉、防洪、供水、运输"]],
   feats:["大型水利需要跨村落协作，被认为推动了早期国家的形成","都江堰（约公元前 256 年）无坝引水，两千多年仍在运行","灌渠与运河同时承担了运输功能"],
   subject:"an ancient wooden chain pump for lifting water — a slatted wooden chain running over a sprocket wheel with a hand crank, weathered wood, plain neutral background, three-quarter view, museum artifact photograph"},
  {id:"medicine", era:"classical", name:"医学", en:"Medicine", year:"约公元前 400 年", roots:["writing"],
   tag:"从巫术与经验走向可传授的医术",
   intro:"《希波克拉底文集》与《黄帝内经》几乎同时把疾病从神罚解释为自然原因。诊断、草药、针灸与外科由此成为可以记录与传授的技艺。",
   specs:[["出现时间","约公元前 400 年（体系化）"],["关键内容","诊断、草药、针灸、外科、脉学"],["代表典籍","《黄帝内经》《伤寒杂病论》《希波克拉底文集》"],["作用","治病、防疫、公共卫生"]],
   feats:["把疾病归因于自然而非神罚，是医学成为科学的第一步","中国的脉诊、针灸与方剂形成独立而完整的体系","与炼金术、解剖学结合后，走向近代医学"],
   subject:"a small bronze acupuncture figure with incised dotted meridian lines, beside a brass mortar with a pestle and a bundle of dried herbs tied with string, on a plain neutral surface, museum artifact photograph, no readable text"},
  {id:"philosophy", era:"classical", name:"哲学与逻辑", en:"Philosophy & Logic", year:"约公元前 600 年", roots:["writing","mathematics"],
   tag:"人类开始为「为什么」而不是「怎么做」提问",
   intro:"从希腊的苏格拉底、柏拉图、亚里士多德到中国的孔孟老庄，人类第一次系统地追问世界是什么、人应当如何生活。逻辑学与论证方法由此诞生。",
   specs:[["出现时间","约公元前 600 年（轴心时代）"],["关键内容","逻辑、伦理、认识论、自然哲学"],["代表","亚里士多德逻辑学、诸子百家"],["影响","科学方法、法律、教育"]],
   feats:["亚里士多德的三段论是形式逻辑的起点，延续两千余年","中国诸子百家奠定了此后两千年的思想底色","「用理由说服人」取代「用权威压服人」，是科学的思维前提"],
   subject:"an abstract minimalist 3D rendering of two balanced geometric solids — a polished sphere resting on top of a matte cube — sitting on a thin beam, soft gray background, conceptual visualization"},

  /* ==================== 中世纪 ==================== */
  {id:"paper", era:"medieval", name:"造纸术", en:"Papermaking", year:"105 年", roots:["writing"],
   tag:"让书写材料从奢侈品变成日常用品",
   intro:"蔡伦改进造纸术，用树皮、麻头与破布造出廉价耐用的纸。相比竹简、莎草纸与羊皮纸，纸更轻、更便宜、产量更大，直接决定了此后书籍与知识的普及速度。",
   specs:[["出现时间","105 年（中国东汉，蔡伦改进）"],["原料","麻、树皮、破布、竹"],["关键工艺","浸泡、打浆、抄纸、压榨、晾晒"],["影响","书籍、行政、教育、印刷"]],
   feats:["纸的成本不到羊皮纸的百分之一，使书籍大规模复制成为可能","造纸术经阿拉伯世界传入欧洲，历时约一千年","没有纸，印刷术就不会有真正的社会影响"],
   subject:"a stack of handmade laid-paper sheets with visible fibers and deckled edges, beside a wooden papermaking mould with a fine screen, on a plain neutral surface, museum artifact photograph, no text"},
  {id:"printing", era:"medieval", name:"印刷术", en:"Printing", year:"约 1040 年", roots:["paper"],
   tag:"第一次让信息可以批量复制",
   intro:"从雕版到毕昇的活字，印刷把「抄书」变成「印书」。古腾堡在十五世纪把活字与压印机结合，书籍价格骤降，思想传播速度随之改变，宗教改革与科学革命都建立在印刷之上。",
   specs:[["出现时间","约 7 世纪雕版，1040 年活字（毕昇）"],["关键技术","雕版、活字、油墨、压印机"],["材料","木、泥、铜、铅合金"],["影响","书籍、教育、宗教改革、科学传播"]],
   feats:["活字把排版拆成可重组的单元，是「标准化零件」思想的早期实践","印刷使同一文本可以被无数学者同时引用与检验","知识复制成本下降，是科学共同体得以形成的前提"],
   subject:"an ancient movable-type printing set: a compartmented wooden case filled with rows of small carved wooden type blocks bearing faint illegible carved marks, with a wooden printing frame and an ink brush beside it, plain neutral background, three-quarter view"},
  {id:"compass", era:"medieval", name:"指南针", en:"Compass", year:"约 1040 年", roots:["iron"],
   tag:"让方向不再依赖天气与地标",
   intro:"从司南到水浮磁针，中国在十一世纪已把指南针用于航海。有了它，船在阴天与远海也能辨明方向，远洋航线第一次可以不靠海岸线延伸。",
   specs:[["出现时间","约公元前 4 世纪（司南），11 世纪航海应用"],["原理","磁针指向地磁南北"],["形态","水浮针、旱罗盘、磁罗盘、电子罗盘"],["作用","航海、测绘、勘探"]],
   feats:["指南针经阿拉伯传入欧洲，成为大航海的关键装备","从磁针到陀螺罗盘与卫星导航，定向技术不断换代","「磁场能隔空作用」的现象，六百年后启发了电磁学研究"],
   subject:"two ancient Chinese compasses: a small bronze circular plate engraved with concentric rings and a spoon-shaped lodestone resting in its center, beside a round wooden box compass with a thin needle, on a plain neutral surface, museum artifact photograph"},
  {id:"ocean-ship", era:"medieval", name:"远洋帆船", en:"Ocean-going Ship", year:"约 1200 年", roots:["sailing","compass"],
   tag:"舵、多桅与三角帆的组合，让船真正能远航",
   intro:"尾舵、多桅多帆与三角帆的组合，使帆船可以逆风前进、稳定转向、按需调整帆面。中国的福船与宝船、欧洲的卡拉维尔与盖伦，把远洋航线连成一张网。",
   specs:[["出现时间","约 1200 年（成熟形态）"],["关键结构","尾舵、多桅多帆、水密隔舱、三角帆"],["材料","木材、铁钉、麻绳、帆布"],["用途","远洋贸易、探索、运输"]],
   feats:["水密隔舱（中国发明）让一两个舱进水也不致沉船","尾舵使船能在远海稳定保持航向","郑和船队（1405—1433）七下西洋，是当时规模最大的远洋航行"],
   subject:"a museum-style scale model of a large Chinese treasure ship with a tall stern rudder, several masts with battened sails, a high stern castle and a wooden hull, sitting on a plain light-gray surface, three-quarter view, no text"},
  {id:"alchemy", era:"medieval", name:"炼金术与蒸馏", en:"Alchemy & Distillation", year:"约 800 年", roots:["medicine","philosophy"],
   tag:"一门失败的科学，却留下了全套实验方法",
   intro:"炼金术士想点石成金、炼出长生药，目标虽然落空，却发明了蒸馏、结晶、升华与过滤等实验技术，也发现了硫酸、硝酸与酒精，为近代化学铺好了路。",
   specs:[["出现时间","约 800 年（阿拉伯炼金术）"],["代表","贾比尔、拉齐、中国炼丹术"],["关键方法","蒸馏、结晶、升华、溶解、煅烧"],["遗产","实验器皿、提纯工艺、矿物酸"]],
   feats:["蒸馏器与曲颈瓶，是现代化学实验室器皿的直系祖先","火药、酒精、矿物酸都出自炼丹与炼金的炉边","「可重复的实验」这个习惯，比它的目标更有价值"],
   subject:"an alchemist's glass distillation apparatus — a round-bottom flask, an alembic head with a curved spout and a small receiving flask — on a plain neutral surface beside a brass mortar and pestle, museum artifact photograph"},
  {id:"gunpowder", era:"medieval", name:"火药", en:"Gunpowder", year:"约 850 年", roots:["alchemy"],
   tag:"第一种化学爆炸物",
   intro:"炼丹士在配药时意外得到会猛烈燃烧的混合物——硝石、硫黄与木炭。火药先用于烟火与火器，随后重塑了战争、采矿与工程，也第一次把「爆炸」变成可控的力学工具。",
   specs:[["出现时间","约 850 年（中国唐代）"],["成分","硝石、硫黄、木炭"],["用途","火器、烟火、采矿、爆破、火箭"],["关键影响","火药武器终结了城堡与骑士时代"]],
   feats:["火药武器让攻城战与军队组织彻底改变","同样的推进原理，在二十世纪变成火箭与运载器","采矿爆破让隧道与矿产开发成为可能"],
   subject:"a small pile of coarse black gunpowder grains beside an ancient bronze hand cannon and a bamboo fire-arrow tube, on a plain neutral surface, museum artifact photograph, no text"},
  {id:"clock", era:"medieval", name:"机械钟", en:"Mechanical Clock", year:"约 1280 年", roots:["iron","mathematics"],
   tag:"把时间变成可以被机器切分的东西",
   intro:"擒纵机构让重锤或发条驱动齿轮匀速转动，钟楼与座钟第一次把一天切分成小时与分钟。有了精确的时间，工厂、铁路、航海与实验才谈得上同步与配准。",
   specs:[["出现时间","约 1280 年（欧洲机械钟）"],["关键机构","擒纵器、齿轮、重锤、发条、摆"],["精度","日误差分钟级 → 秒级 → 原子钟十亿分之一秒"],["作用","计时、天文、航海、工业节拍"]],
   feats:["擒纵机构是机械自动控制最早的成功案例","精密航海钟（18 世纪）把经度测定变成可能","把时间标准化，是铁路时刻表与工厂制度的前提"],
   subject:"an antique brass mechanical clock movement with visible interlocking gears, a coiled mainspring, a verge escapement and a swinging pendulum, mounted on a plain neutral surface, museum artifact photograph, no dial, no numbers"},
  {id:"university", era:"medieval", name:"大学与学术", en:"University", year:"1088 年", roots:["philosophy","writing"],
   tag:"把求知变成可以常设的机构",
   intro:"博洛尼亚、巴黎、牛津等大学让教师与学生结成持久的行会式团体。课程、学位、辩论与图书馆被制度化，学术从此不再依赖个别赞助人，而能一代代积累。",
   specs:[["出现时间","1088 年（博洛尼亚大学）"],["组织","学院、学位、课程、教师行会"],["核心方法","讲授、辩论、注释、质疑"],["影响","科学、法律、医学、行政人才"]],
   feats:["「质疑与辩论」被写入教学制度，为科学革命准备了方法","大学保存并传递了古代典籍，直到它们重新被读通","学位制度使知识认证标准化，今天通行全球"],
   subject:"an abstract minimalist 3D rendering of a neat stack of thick old leather-bound books topped with a small brass oil lamp, warm muted palette, soft gray background, conceptual visualization, no text"},

  /* ==================== 大航海与科学革命 ==================== */
  {id:"ocean-navigation", era:"renaissance", name:"远洋航行", en:"Ocean Navigation", year:"1492 年", roots:["ocean-ship","compass"],
   tag:"人类第一次把整个地球表面连成一张网",
   intro:"有了能远航的船、能定向的罗盘与能记录的海图，船队绕开陆地直入大洋。新航路把美洲、非洲、亚洲与欧洲连成一个交换体系，也带来了物种、人口与疾病的全球大交换。",
   specs:[["出现时间","1492 年（哥伦布抵达美洲）"],["关键条件","远洋帆船、罗盘、海图、天文定位"],["代表航程","郑和下西洋、哥伦布、麦哲伦环球"],["影响","全球贸易、物种交换、殖民与移民"]],
   feats:["麦哲伦船队（1519—1522）首次环球航行，证明地球可以绕行","玉米、马铃薯、辣椒与番薯传入中国，改变了粮食结构","全球航线网是后来海底电缆与集装箱航运的雏形"],
   subject:"a museum-style scale model of a 15th century three-masted caravel with a high stern castle, a lateen sail on the mizzen mast and square sails on the fore and main masts, sitting on a plain light-gray surface, three-quarter view, no text"},
  {id:"heliocentrism", era:"renaissance", name:"日心说与天文革命", en:"Heliocentrism", year:"1543 年", roots:["astronomy","printing"],
   tag:"人类把自己从宇宙中心挪开",
   intro:"哥白尼提出太阳而非地球是中心，开普勒用椭圆轨道修正行星运动，伽利略用望远镜看到木星卫星。天文学从「解释经典」变成「观测与计算」。",
   specs:[["出现时间","1543 年（《天体运行论》）"],["关键人物","哥白尼、开普勒、伽利略"],["关键证据","行星轨道、木星卫星、金星相位"],["影响","世界观、力学、科学方法"]],
   feats:["椭圆轨道取代圆轨道，使预测精度第一次远超经验公式","伽利略的观测与教会的冲突，确立了「观测优先于权威」","为万有引力定律提供了直接的问题与数据"],
   subject:"an antique brass orrery — a small mechanical model of the solar system with a central brass sun and tiny planets on thin revolving arms — on a plain neutral surface, three-quarter view, museum artifact photograph, no text"},
  {id:"anatomy", era:"renaissance", name:"解剖与生理", en:"Anatomy & Physiology", year:"1543 年", roots:["medicine","printing"],
   tag:"用亲手解剖纠正沿用千年的错误",
   intro:"维萨里的《人体构造》以亲自解剖为依据重写了人体图谱，哈维用实验证明血液是循环而非不断生成。医学第一次建立在可验证的观察之上。",
   specs:[["出现时间","1543 年（《人体构造》）；1628 年（血液循环）"],["关键方法","解剖、观察、定量实验"],["关键发现","血液循环、器官结构"],["影响","外科、生理学、近代医学"]],
   feats:["血液循环的定量论证（心脏输出量远超血液总量）是实验生理学的典范","解剖图谱靠印刷术迅速传遍欧洲","解剖学是所有外科学与医学教育的基础"],
   subject:"a set of antique anatomical instruments — a steel scalpel, a pair of fine forceps and a small brass caliper — laid neatly beside a wax anatomical model of a human heart, on a plain neutral surface, museum artifact photograph"},
  {id:"optics", era:"renaissance", name:"光学与透镜", en:"Optics & Lenses", year:"1608 年", roots:["mathematics","alchemy"],
   tag:"把「看得见」的边界向外推远、向内深入",
   intro:"磨制透镜的工匠做出了望远镜与显微镜：前者把视野推到木星与土星环，后者第一次揭示细胞与微生物。人类的感觉第一次被仪器放大。",
   specs:[["出现时间","1608 年（望远镜）；约 1590 年（显微镜）"],["关键内容","折射定律、透镜成像、消色差"],["关键工具","望远镜、显微镜、棱镜"],["影响","天文学、生物学、医学、光谱学"]],
   feats:["显微镜让「细胞」与「细菌」进入人类的词汇","折射定律把光学变成可以计算的科学","后来的光谱分析、摄影与激光都源自光学"],
   subject:"an antique brass refracting telescope with a long tapered tube and a leather-wrapped barrel, lying diagonally beside a small brass compound microscope with a rack-and-pinion focus, on a plain neutral surface, museum artifact photograph, no text"},
  {id:"calculus", era:"renaissance", name:"解析几何与微积分", en:"Calculus", year:"1665 年", roots:["mathematics","philosophy"],
   tag:"第一次能精确描述「变化」本身",
   intro:"笛卡儿把代数与几何合而为一，牛顿与莱布尼茨各自发明微积分，用极限与无穷小处理变化率与累积量。运动、光学与天文学由此获得了统一的数学语言。",
   specs:[["出现时间","1637 年（解析几何）；1665—1684 年（微积分）"],["关键人物","笛卡儿、牛顿、莱布尼茨"],["核心工具","函数、坐标、导数、积分、微分方程"],["影响","物理、工程、经济、一切定量科学"]],
   feats:["坐标把几何问题变成代数运算，是计算化思维的起点","微分方程成为描述自然规律的标准形式","微积分是此后三百年工程与物理的共同语言"],
   subject:"an abstract minimalist 3D rendering of a glowing white straight tangent line touching a smooth curved surface at a single point, thin coordinate grid lines fading into a soft gray background, conceptual visualization, no text"},
  {id:"vacuum", era:"renaissance", name:"真空与大气压", en:"Vacuum & Atmospheric Pressure", year:"1643 年", roots:["alchemy","clock"],
   tag:"证明「空无」存在，并第一次量出空气的重量",
   intro:"托里拆利用水银柱制出真空并读出气压，帕斯卡把气压计搬上山验证大气随高度变薄，玻意耳发现气体的压强与体积成反比。真空与气压从此成为可以操纵的物理量。",
   specs:[["出现时间","1643 年（托里拆利）"],["关键人物","托里拆利、帕斯卡、玻意耳、格里克"],["关键实验","水银气压计、马德堡半球"],["影响","蒸汽机、气泵、气象学、化学"]],
   feats:["马德堡半球实验用十几匹马才拉开抽成真空的两半球","气压随高度下降，第一次让高度测量有了一致标准","气缸与活塞中的气压差，正是蒸汽机做功的原理"],
   subject:"an antique mercury barometer — a tall brass-framed vertical glass tube standing in a small glass cistern of mercury, with a plain graduated brass scale plate without numerals, on a plain neutral surface, museum artifact photograph"},
  {id:"mechanics", era:"renaissance", name:"经典力学", en:"Classical Mechanics", year:"1687 年", roots:["calculus","heliocentrism"],
   tag:"用三条定律解释从苹果到行星的一切运动",
   intro:"牛顿在《自然哲学的数学原理》中提出运动三定律与万有引力，把地面上的落体与天上的行星统一在同一套方程里。这是人类第一次用一个理论覆盖整片可见世界。",
   specs:[["出现时间","1687 年（《自然哲学的数学原理》）"],["核心内容","运动三定律、万有引力、动量守恒"],["关键工具","微积分、实验与观测"],["影响","工程、天文、机械、航天"]],
   feats:["「同一个力既让苹果落地也让月亮绕行」，是科学统一性的典范","三定律至今是桥梁、机械与轨道的设计基础","从火箭入轨到登月，用的仍是这套十七世纪的方程"],
   subject:"an antique brass pendulum demonstration apparatus with a heavy brass bob on a thin rod, mounted on a wooden stand beside a small inclined plane with a rolling brass ball, plain neutral surface, museum artifact photograph"},

  /* ==================== 工业时代 ==================== */
  {id:"steam-engine", era:"industrial", name:"蒸汽机", en:"Steam Engine", year:"1712 年", roots:["vacuum","mechanics"],
   tag:"人类第一次把燃料变成可以随处使用的动力",
   intro:"纽科门用大气压差驱动活塞抽水，瓦特加上独立冷凝器与旋转输出，把蒸汽机从抽水装置变成通用动力机。工厂第一次可以建在没有河流的地方。",
   specs:[["出现时间","1712 年（纽科门）；1769 年（瓦特改良）"],["原理","燃料加热产生蒸汽，蒸汽推动活塞做功"],["关键改进","独立冷凝器、双向气缸、离心调速器"],["影响","矿业、纺织、铁路、轮船"]],
   feats:["第一次把化学能稳定转成机械功，摆脱了对水与风的依赖","离心调速器是最早的自动反馈控制装置之一","蒸汽机带动铁路与轮船，把世界的时间与距离一起压缩"],
   subject:"an antique cast-iron stationary steam engine — a large vertical cylinder, a polished spoked flywheel and a brass centrifugal governor — standing on a plain light-gray museum surface, three-quarter view, no text"},
  {id:"textile-machinery", era:"industrial", name:"纺织机械", en:"Textile Machinery", year:"1764 年", roots:["weaving","steam-engine"],
   tag:"工业革命从纺纱机开始",
   intro:"飞梭、珍妮纺纱机、水力纺纱机与动力织布机把纺与织逐步机械化，一名工人能照看的纱锭从一枚变成上百枚。纺织业因此成为第一个真正的工厂化产业。",
   specs:[["出现时间","1733 年飞梭；1764 年珍妮机；1785 年动力织布机"],["关键发明","飞梭、珍妮纺纱机、水力纺纱机、骡机"],["动力","人力 → 水力 → 蒸汽"],["影响","工厂制度、工人运动、棉纺织贸易"]],
   feats:["是历史上第一个被全面机械化的行业","工厂制度与大规模雇佣劳工由此形成","棉花贸易把印度、美洲与欧洲工厂连成了一体"],
   subject:"an antique wooden spinning jenny with a row of spindles, a turned wooden frame and a hand-cranked wheel, beside a wooden hand shuttle and a spool of cotton thread, on a plain neutral surface, museum artifact photograph, no text"},
  {id:"coke-iron", era:"industrial", name:"焦炭炼铁与钢铁", en:"Coke Smelting & Steel", year:"1709 年", roots:["iron"],
   tag:"让钢铁从稀缺材料变成工业的通用骨架",
   intro:"用焦炭替代木炭炼铁，摆脱了森林对冶铁的束缚；贝塞麦转炉与平炉炼钢又让钢的产量猛增、价格大跌。钢轨、钢船与钢筋因此成为可能。",
   specs:[["出现时间","1709 年（焦炭炼铁）；1856 年（转炉炼钢）"],["关键工艺","焦炭高炉、搅炼、转炉、平炉、连铸"],["关键指标","钢产量与钢价"],["影响","铁路、桥梁、船舶、建筑、机械"]],
   feats:["焦炭使冶铁产量在一个世纪内增长十倍以上","转炉把炼钢时间从数天缩短到十几分钟","钢材成为现代基础设施与交通工具的通用材料"],
   subject:"a group of industrial steel artifacts — several dark cast-iron ingots, a hand-forged steel billet and a pair of blacksmith's tongs — arranged on a plain light-gray surface, museum artifact photograph, no text"},
  {id:"chemistry", era:"industrial", name:"近代化学", en:"Modern Chemistry", year:"1789 年", roots:["alchemy","vacuum"],
   tag:"把物质变化写成可以称量的方程式",
   intro:"拉瓦锡用精密天平证明燃烧是氧化而非「放出燃素」，并列出第一张元素表。此后道尔顿提出原子论，门捷列夫排出周期表，化学成为有守恒定律与结构规律的实验科学。",
   specs:[["出现时间","1789 年（《化学基本论述》）"],["关键人物","拉瓦锡、道尔顿、门捷列夫"],["核心概念","质量守恒、元素、原子、周期律"],["影响","化工、材料、医药、农业"]],
   feats:["定量测量把化学从配方经验变成可计算的理论","元素周期表成功预测了尚未被发现的元素","化肥、染料、药品、塑料都建立在近代化学之上"],
   subject:"an antique brass balance scale with two hanging pans and a small set of brass weights, beside a rack of glass chemical vessels — flasks and beakers — on a plain neutral surface, museum artifact photograph, no numerals, no text"},
  {id:"railway", era:"industrial", name:"铁路与蒸汽机车", en:"Railway", year:"1825 年", roots:["steam-engine","coke-iron"],
   tag:"第一次让陆上运输摆脱马匹的体力与耐力",
   intro:"钢轨降低摩擦、机车提供动力，铁路的运量与速度都远超马车。它把内陆市场与港口连成一体，也第一次让「标准时间」成为必需——列车时刻表不能容忍各地各过各的钟。",
   specs:[["出现时间","1825 年（斯托克顿—达灵顿）；1830 年（利物浦—曼彻斯特）"],["关键要素","钢轨、蒸汽机车、隧道、桥梁、信号"],["早期速度","约 30—60 km/h"],["影响","工业化、城市化、标准时间、旅游"]],
   feats:["铁路运量是马车的数十倍，运费则下降一个数量级","各地为对齐时刻表而采用统一时区，时间由此被标准化","铁路与电报一起，完成了十九世纪的「时空压缩」"],
   subject:"a museum-style scale model of an early steam locomotive with a tall smokestack, a small driver cab and four spoked wheels, standing on a short straight section of miniature rail, on a plain light-gray surface, three-quarter view, no text"},
  {id:"electromagnetism", era:"industrial", name:"电磁学", en:"Electromagnetism", year:"1831 年", roots:["chemistry","mechanics"],
   tag:"把电与磁统一，也让电第一次可以大规模产生",
   intro:"奥斯特发现电流旁磁针偏转，法拉第发现磁能生电，麦克斯韦用四个方程把它们写成统一理论，并预言了电磁波。电力时代由此打开。",
   specs:[["出现时间","1820 年（奥斯特）；1831 年（电磁感应）；1865 年（麦克斯韦方程组）"],["关键概念","电流、磁场、感应、电磁波"],["关键应用","发电机、电动机、变压器、无线电"],["影响","电力、通信、电子"]],
   feats:["电磁感应让机械能变成电能、电能又变回动力，构成现代电力系统","麦克斯韦预言电磁波存在，二十年后被赫兹验证","统一电与磁，是物理学「统一之路」的第一个成功范例"],
   subject:"an antique electromagnetic induction apparatus — a copper wire coil wound on a wooden spool mounted on a base, with a small moving-coil galvanometer with a blank scale and a horseshoe magnet beside it, on a plain neutral surface, museum artifact photograph"},
  {id:"germ-theory", era:"industrial", name:"病菌学说与疫苗", en:"Germ Theory & Vaccines", year:"1796 年", roots:["anatomy","chemistry"],
   tag:"把疾病归因于可以找到、也可以防住的微生物",
   intro:"琴纳用牛痘接种预防天花，巴斯德证明微生物导致腐败与疾病，科赫分离出结核与霍乱病原体。消毒、疫苗与公共卫生让人类的平均寿命第一次持续上升。",
   specs:[["出现时间","1796 年（天花疫苗）；1861 年（巴斯德）；1876 年（科赫）"],["关键内容","病原微生物、灭菌消毒、疫苗、免疫"],["关键人物","琴纳、巴斯德、科赫、李斯特"],["影响","外科手术、公共卫生、预期寿命"]],
   feats:["天花在 1980 年被宣布消灭，是人类唯一根除的传染病","无菌手术让外科死亡率大幅下降","疫苗与清洁饮水，是二十世纪人均寿命增长的最大贡献者之一"],
   subject:"a set of antique medical artifacts — a small glass vaccine vial with a cork stopper, a brass syringe with a glass barrel and a steel surgical scalpel — arranged on a plain neutral surface, museum artifact photograph, no text"},
  {id:"evolution", era:"industrial", name:"演化论", en:"Theory of Evolution", year:"1859 年", roots:["anatomy"],
   tag:"把生命的多样性解释成一个可以检验的过程",
   intro:"达尔文与华莱士提出自然选择：变异、遗传与生存竞争共同塑造物种。演化论把生物学从描述性学科变成有统一机制的科学，也为遗传学与分子生物学留出了接口。",
   specs:[["出现时间","1859 年（《物种起源》）"],["核心机制","变异、遗传、自然选择、共同祖先"],["关键人物","达尔文、华莱士、孟德尔"],["影响","生物学、医学、农业、人类学"]],
   feats:["「共同祖先」把地球上所有生命放进同一棵谱系树","孟德尔遗传学后来为自然选择提供了物质机制","抗生素耐药与病毒变异，今天仍在印证这套机制"],
   subject:"an abstract minimalist 3D rendering of a stylized branching tree of glowing translucent nodes and connecting branches, from a single trunk to many tips, soft gray background, conceptual visualization, no text"},

  /* ==================== 电气与原子时代 ==================== */
  {id:"electric-power", era:"electric", name:"电力系统", en:"Electric Power", year:"1882 年", roots:["electromagnetism","steam-engine"],
   tag:"让能源变成可以远距离输送的商品",
   intro:"爱迪生的直流电站与特斯拉、西屋的交流系统，把发电机、变压器与输电线连成电网。电力可以在几百公里外被生产，再送到每一台机器与每一盏灯前。",
   specs:[["出现时间","1879 年（白炽灯）；1882 年（珍珠街电站）"],["关键要素","发电机、变压器、交流输电、电网调度"],["关键人物","爱迪生、特斯拉、西屋"],["影响","工业、照明、家电、城市形态"]],
   feats:["交流变压使电力可以高压远送，电网规模不再受距离限制","电力把工厂从蒸汽机的传动轴中解放出来","抽水蓄能与后来的清洁电源，都是从电网发展出的调节手段"],
   subject:"a set of antique electrical artifacts — a large glass incandescent light bulb with a brass screw base, a small AC induction motor with a copper coil winding and a laminated iron core — arranged on a plain neutral surface, museum artifact photograph, no text"},
  {id:"internal-combustion", era:"electric", name:"内燃机", en:"Internal Combustion Engine", year:"1886 年", roots:["steam-engine","chemistry"],
   tag:"把动力装进口袋大小的地方",
   intro:"奥托的四冲程循环与狄塞尔的压燃式发动机把燃料直接烧在气缸里，热效率远高于外燃的蒸汽机。它体积小、启动快，让汽车、飞机、船舶与农机都成为可能。",
   specs:[["出现时间","1876 年（奥托四冲程）；1892 年（狄塞尔）"],["循环","四冲程、压燃式"],["燃料","汽油、柴油、天然气、生物燃料"],["影响","汽车、航空、船舶、农机、工程机械"]],
   feats:["热效率比蒸汽机高出数倍，且不需要锅炉与锅炉工","与石油工业结合，催生了二十世纪的能源结构","今天正与电机混合，转向电动化与低碳燃料"],
   subject:"an antique cutaway four-cylinder internal combustion engine model — a cast-iron block with exposed pistons, a crankshaft, a carburetor and a distributor with spark plug wires — on a plain light-gray surface, museum artifact photograph, no text"},
  {id:"aviation", era:"electric", name:"航空", en:"Aviation", year:"1903 年", roots:["mechanics","internal-combustion"],
   tag:"人类第一次把「持续动力飞行」变成现实",
   intro:"莱特兄弟用可控三轴操纵加上轻量内燃机，在 1903 年完成首次持续动力飞行。此后飞机从竞技玩具变成战争工具、邮政运输与大众交通，地球在空间上被真正缩小。",
   specs:[["出现时间","1903 年（莱特兄弟）"],["关键突破","三轴操纵、机翼升力、轻量动力"],["关键人物","莱特兄弟、李林塔尔、容克斯"],["影响","交通、物流、军事、气象、救援"]],
   feats:["「可控」比「有大功率」更关键，莱特兄弟的三大操纵面沿用至今","全金属应力蒙皮与喷气发动机，把航线推向全球","单位座公里油耗与噪声，此后持续下降"],
   subject:"a museum-style scale model of an early 1900s biplane with two stacked fabric-covered wings, thin wire bracing, a small four-cylinder engine and two wooden propellers, on a plain light-gray surface, three-quarter view, no text"},
  {id:"radio", era:"electric", name:"无线电与电子学", en:"Radio & Electronics", year:"1901 年", roots:["electromagnetism","vacuum"],
   tag:"让信息脱离电线",
   intro:"马可尼用电磁波完成跨大西洋通信，此后真空管把微弱信号放大，广播、雷达与电视依次登场。信息第一次可以同时、无差别地送达无数接收者。",
   specs:[["出现时间","1895—1901 年（马可尼）；1906 年（真空三极管）"],["关键元件","火花隙、矿石检波器、真空管、晶体管"],["关键应用","无线电报、广播、雷达、电视、导航"],["影响","通信、传媒、军事、电子工业"]],
   feats:["无线电使跨海通信不再依赖电缆，船舶求救成为可能","真空三极管是第一个放大器件，电子学由此开始","雷达与无线电导航直接改变了第二次世界大战的战术"],
   subject:"an antique radio apparatus — a cylindrical copper spark-gap transmitter coil with a brass induction coil, a black bakelite tuning dial with a blank unmarked face and an early glass vacuum tube glowing faintly — arranged on a plain neutral surface, museum artifact photograph, no numbers"},
  {id:"modern-physics", era:"electric", name:"现代物理学", en:"Modern Physics", year:"1905 年", roots:["mechanics","electromagnetism"],
   tag:"相对论与量子论重建了时间、空间与物质的概念",
   intro:"爱因斯坦的相对论把时间与空间合成一体，普朗克与玻尔的量子论则说明微观世界只能给出概率。这两套理论看似矛盾，却各自精确得惊人，并直接支撑了核能、半导体与激光。",
   specs:[["出现时间","1900 年（量子假说）；1905、1915 年（相对论）"],["关键内容","光速不变、质能等价、光电效应、波粒二象性、不确定性"],["关键人物","普朗克、爱因斯坦、玻尔、海森堡、薛定谔"],["影响","核能、半导体、激光、量子信息"]],
   feats:["质能等价说明质量与能量可以互换，直接指向核能的可能性","量子力学对半导体与激光的解释，是今天所有电子设备的底层原理","相对论修正后的时间信号，是卫星定位精确到米的前提"],
   subject:"an abstract minimalist 3D rendering of two glowing intertwined wave-like ribbons with a small luminous sphere travelling along them, soft gray gradient background, conceptual visualization, no text"},
  {id:"genetics", era:"electric", name:"遗传学", en:"Genetics", year:"1900 年", roots:["evolution","chemistry"],
   tag:"找出「变异与遗传」背后的物质单元",
   intro:"孟德尔在修道院里种豌豆，用统计方法发现遗传因子遵循可预测的规律；1900 年他的论文被重新发现，此后基因、染色体与突变成为生物学的基本概念。",
   specs:[["出现时间","1866 年（孟德尔）；1900 年重新发现"],["关键概念","基因、染色体、显隐性、突变"],["关键人物","孟德尔、摩尔根、费希尔"],["影响","育种、医学、演化生物学、分子生物学"]],
   feats:["用数数（统计比例）推导看不见的遗传机制，是定量生物学的开端","摩尔根的果蝇实验，第一次把基因定位到染色体上","为分子生物学与基因工程提供了概念框架"],
   subject:"a set of antique botanical genetics specimens — a mounted herbarium sheet with pressed pea plants bearing two different flower colors, beside a brass magnifier and a small glass slide box — arranged on a plain neutral surface, museum artifact photograph, no text"},
  {id:"antibiotics", era:"electric", name:"抗生素", en:"Antibiotics", year:"1928 年", roots:["germ-theory","chemistry"],
   tag:"第一种能大规模杀死病原菌的药物",
   intro:"弗莱明发现青霉菌周围的细菌被溶解，弗洛里与钱恩把它变成可用的药物。抗生素让肺炎、伤口感染与手术并发症不再致命，人类寿命在几十年间显著跃升。",
   specs:[["出现时间","1928 年（青霉素发现）；1940 年代（临床使用）"],["作用","抑制或杀灭细菌"],["代表药物","青霉素、链霉素、四环素、头孢菌素"],["影响","感染性疾病、外科手术、公共卫生"]],
   feats:["抗生素让外科手术、化疗与器官移植成为可能","抗菌药耐药菌的出现，成为全球公共卫生挑战","药物研发从偶然发现，走向定向筛选与结构设计"],
   subject:"a set of antique microbiology artifacts — an old glass petri dish containing a dusty green Penicillium mold culture, a small glass ampoule of white powder and a brass inoculating loop — arranged on a plain neutral surface, museum artifact photograph, no text"},
  {id:"nuclear-fission", era:"electric", name:"核裂变与核能", en:"Nuclear Fission", year:"1938 年", roots:["modern-physics","chemistry"],
   tag:"第一次释放原子核内部的能量",
   intro:"哈恩与迈特纳发现重核裂变会释放巨大能量，费米建成第一座反应堆，随后原子弹与核电站相继出现。人类第一次掌握了比化学能高百万倍的能源，也第一次有了自我毁灭的能力。",
   specs:[["出现时间","1938 年（裂变发现）；1942 年（首座反应堆）；1954 年（首座核电站）"],["原理","重核裂变释放能量，维持链式反应"],["关键人物","哈恩、迈特纳、费米"],["影响","核武器、核电、核医学、同位素"]],
   feats:["1 千克铀-235 完全裂变的能量，约相当于 2000 吨石油","核电提供稳定低碳的基荷电力，但废料与安全是长期课题","核医学与同位素测年，成为医学与考古的重要工具"],
   subject:"a museum-style model of an early nuclear reactor core — a stacked lattice of gray graphite bricks with several dark uranium fuel rods inserted and one control rod partly withdrawn, on a plain light-gray surface, three-quarter view, no text"},

  /* ==================== 信息时代 ==================== */
  {id:"computing", era:"information", name:"计算机与信息论", en:"Computing & Information Theory", year:"1936 年", roots:["radio","electric-power"],
   tag:"把「计算」从人脑变成机器",
   intro:"图灵用图灵机给出「可计算」的定义，香农说明信息可以用比特度量，冯·诺依曼设计了存储程序结构。此后 ENIAC、EDSAC 等机器把计算变成电力驱动的自动过程。",
   specs:[["出现时间","1936 年（图灵机）；1945 年（存储程序结构）；1946 年（ENIAC）"],["关键人物","图灵、香农、冯·诺依曼"],["关键概念","可计算性、比特、存储程序、二进制"],["影响","一切数字设备"]],
   feats:["图灵机给出了「什么可以被机械求解」的边界","存储程序结构让同一台机器通过换程序完成不同任务","香农的信息论把通信变成可以定量设计的工程"],
   subject:"a vintage electromechanical relay rack unit with rows of glass-enclosed relays and cloth-insulated wiring, a small panel of unmarked toggle switches and a reel of punched paper tape, on a plain light-gray surface, museum artifact photograph, no letters, no numbers"},
  {id:"transistor", era:"information", name:"晶体管与集成电路", en:"Transistor & Integrated Circuit", year:"1947 年", roots:["modern-physics","chemistry","computing"],
   tag:"用一块半导体取代整柜电子管",
   intro:"贝尔实验室做出点接触晶体管，此后硅平面工艺把成千上万只晶体管做在同一片晶圆上。体积、功耗与成本同时暴跌，电子设备从此可以做到口袋大小。",
   specs:[["出现时间","1947 年（晶体管）；1958 年（集成电路）；1971 年（微处理器）"],["关键人物","肖克利、巴丁、布拉顿、基尔比、诺伊斯"],["关键工艺","掺杂、光刻、平面工艺"],["影响","计算机、通信、消费电子、一切嵌入式设备"]],
   feats:["摩尔定律观察到芯片上的晶体管数量约每两年翻一番，持续了半个世纪","集成电路使单位计算成本下降上亿倍","半导体是今天能源、通信与人工智能共同的硬件底座"],
   subject:"a single vintage silicon transistor beside an early integrated circuit — a round metal-can transistor with gold leads next to a small ceramic flat-pack chip with visible gold bond wires and a tiny bare silicon die — arranged on a plain neutral surface, extreme macro photograph, no text"},
  {id:"spaceflight", era:"information", name:"航天", en:"Spaceflight", year:"1957 年", roots:["aviation","nuclear-fission"],
   tag:"人类第一次离开地球并长期留在轨道上",
   intro:"第一颗人造卫星入轨、加加林进入太空、阿波罗登月，航天把火箭、制导与生命保障技术变成探索与基础设施。通信、导航、气象与遥感如今都由卫星承担。",
   specs:[["出现时间","1957 年（首颗人造卫星）；1961 年（首次载人）；1969 年（登月）"],["关键要素","多级火箭、轨道力学、生命保障、制导"],["关键人物","齐奥尔科夫斯基、戈达德、冯·布劳恩、科罗廖夫"],["影响","通信、导航、气象、遥感、科学"]],
   feats:["多级结构与第一宇宙速度，是航天工程的两道门槛","登月计划带动了集成电路、材料与软件的大规模投入","卫星导航与气象预报，已成为日常生活的隐形基础设施"],
   subject:"a museum-style scale model of a multi-stage space launch vehicle standing vertically with four strap-on boosters and a small crew capsule on top, on a plain light-gray surface, full side view, no text"},
  {id:"dna", era:"information", name:"分子生物学与基因工程", en:"Molecular Biology & Genetic Engineering", year:"1953 年", roots:["genetics","chemistry"],
   tag:"找到遗传信息的载体，并学会读写它",
   intro:"沃森与克里克提出 DNA 双螺旋结构，此后遗传密码被破译，限制性内切酶与连接酶让基因可以被剪切与拼接。人类第一次可以改写其他物种的遗传信息。",
   specs:[["出现时间","1953 年（双螺旋）；1973 年（重组 DNA）"],["关键人物","沃森、克里克、富兰克林、桑格"],["关键工具","双螺旋、遗传密码、限制酶、测序、PCR"],["影响","育种、医药、法医、生物产业"]],
   feats:["双螺旋结构解释了遗传信息如何被复制与传递","重组 DNA 让胰岛素、生长激素等药物可以工业化生产","测序技术把读取一个基因组的时间，从十余年压缩到一天以内"],
   subject:"a museum-style physical model of the DNA double helix — two spiral ribbons of alternating wooden blocks connected by pairs of colored rods — standing on a plain light-gray surface, three-quarter view, no text"},
  {id:"internet", era:"information", name:"互联网", en:"Internet", year:"1969 年", roots:["computing"],
   tag:"把计算机连成一张没有中心的网",
   intro:"ARPANET 用分组交换把几台计算机连起来，TCP/IP 让异构网络互通，万维网则给这张网装上了统一的界面。信息第一次可以几乎零成本地复制与分发。",
   specs:[["出现时间","1969 年（ARPANET）；1983 年（TCP/IP）；1989 年（万维网）"],["关键人物","瑟夫、卡恩、伯纳斯-李"],["关键技术","分组交换、TCP/IP、超文本、光纤、域名系统"],["影响","通信、传媒、商业、社交、知识获取"]],
   feats:["分组交换与去中心结构，使网络没有单一故障点","万维网用超链接把全球文档连成一本可以跳转的书","光纤与激光让海底光缆承担了跨洲流量的绝大部分"],
   subject:"an abstract minimalist 3D rendering of a globe-shaped mesh of glowing nodes and connecting lines, a few hubs slightly larger with light travelling along the links, soft gray background, conceptual visualization, no text"},
  {id:"medical-imaging", era:"information", name:"医学影像", en:"Medical Imaging", year:"1971 年", roots:["modern-physics","computing"],
   tag:"第一次能不切开身体就看到体内",
   intro:"X 射线、超声、CT、MRI 与 PET 用不同物理原理把人体内部成像。诊断从「凭症状推测」变成「看得见病灶」，外科与肿瘤治疗因此可以精准规划。",
   specs:[["出现时间","1895 年（X 射线）；1971 年（CT）；1977 年（MRI）"],["关键原理","X 射线吸收、超声反射、核磁共振、放射性示踪"],["关键人物","伦琴、豪斯菲尔德、科马克、劳特伯"],["影响","诊断、外科、肿瘤、胎儿检查"]],
   feats:["CT 把重建数学引入医学，是算法与医学结合的早期范例","MRI 不使用电离辐射，却能分辨软组织","影像数据与人工智能结合，正在走向辅助诊断"],
   subject:"a set of vintage medical imaging artifacts — an early glass X-ray tube with a metal cathode and a small brass collimator, beside several dark radiographic film sheets — arranged on a plain neutral surface, museum artifact photograph, no text"},
  {id:"software", era:"information", name:"软件与个人计算", en:"Software & Personal Computing", year:"1975 年", roots:["transistor","internet"],
   tag:"让硬件通过指令获得无限种用途",
   intro:"编译语言、操作系统与图形界面把计算机从专业工具变成人人可用的设备；个人电脑、开源生态与互联网分发又让软件成为一个独立产业。硬件决定上限，软件决定它能做什么。",
   specs:[["出现时间","1950 年代高级语言；1975 年（个人电脑）；1984 年（图形界面）"],["关键内容","编程语言、操作系统、编译器、图形界面、开源"],["关键人物","巴克斯、里奇、汤普森、斯托曼"],["影响","办公、娱乐、科研、工业、全社会的数字化"]],
   feats:["高级语言把编程从机器码中解放出来，软件规模由此可以增长","图形界面与鼠标让非专业用户也能使用计算机","开源协作让基础设施软件可以全球共同维护"],
   subject:"a vintage early-1980s personal computer — a beige wedge-shaped all-in-one case with a small built-in CRT screen glowing a plain blank gray, a separate mechanical keyboard and a slim floppy disk drive — on a plain light-gray surface, three-quarter view, museum artifact photograph, no letters, no numbers"},

  /* ==================== 数字与智能时代 ==================== */
  {id:"mobile-internet", era:"digital", name:"移动互联网与智能手机", en:"Mobile Internet", year:"2007 年", roots:["internet","transistor"],
   tag:"把互联网放到每个人的口袋里",
   intro:"电容触屏、移动芯片与无线宽带让手机变成随身计算机。任何人都可以随时联网、拍照、支付、导航与创作，信息与服务的获取门槛降到了历史最低。",
   specs:[["出现时间","1990 年代移动电话；2007 年（现代智能手机）"],["关键技术","触屏、移动芯片、3G/4G/5G、应用商店、移动支付"],["典型形态","触屏手机与可穿戴设备"],["影响","社交、电商、支付、出行、内容创作"]],
   feats:["全球手机用户数远超个人电脑，成为最普及的计算设备","应用商店把软件分发成本降到接近零","移动支付与位置服务，重构了线下的消费与出行"],
   subject:"a modern black touchscreen smartphone lying flat on a plain light-gray surface with its screen showing a plain soft gradient and no icons, beside a small pair of white wireless earbuds, top-down macro photograph, no logos, no text"},
  {id:"search-cloud", era:"digital", name:"云计算与大数据", en:"Cloud Computing & Big Data", year:"2006 年", roots:["internet","software"],
   tag:"让算力像水电一样按需取用",
   intro:"把成千上万台服务器组成集群，通过虚拟化按需分配，再把海量日志沉淀成数据资产。企业不再需要自建机房，个人也能在几分钟内得到上千台机器的算力。",
   specs:[["出现时间","2006 年（云计算服务化）"],["关键技术","虚拟化、分布式存储、容器、并行计算、数据仓库"],["典型形态","公有云 / 私有云 / 混合云"],["影响","创业成本、科研计算、推荐系统、人工智能"]],
   feats:["虚拟化与弹性伸缩，把固定资产投入变成按量计费","分布式存储与计算让「用普通机器做大数据」成为现实","集中算力与数据，是机器学习爆发的直接前提"],
   subject:"an abstract minimalist 3D rendering of a glowing server rack made of many thin stacked blades with a few luminous data paths running through them, soft gray background, conceptual visualization, no text"},
  {id:"machine-learning", era:"digital", name:"机器学习与深度学习", en:"Machine Learning & Deep Learning", year:"2012 年", roots:["software","search-cloud"],
   tag:"机器不再靠人写规则，而是从数据里自己找规律",
   intro:"反向传播、卷积网络与大模型的规模扩展，让机器在图像识别、语音转写与自然语言理解上超过传统方法。同一个网络结构，换一份数据就能换一种用途。",
   specs:[["出现时间","1986 年（反向传播普及）；2012 年（深度网络在图像识别上突破）"],["关键概念","神经网络、梯度下降、注意力机制、预训练"],["关键条件","数据、算力、算法"],["影响","识别、翻译、推荐、生成、科学研究"]],
   feats:["用「从数据中学习」替代「人工编写规则」，是编程范式的转变","规模扩展（数据、参数、算力）持续带来能力跃升","深度学习已成为材料、生物、气象等领域的通用工具"],
   subject:"an abstract minimalist 3D rendering of a layered neural network — several vertical planes of small glowing nodes densely connected by fine luminous lines between adjacent layers, soft gray background, conceptual visualization, no text"},
  {id:"genome-editing", era:"digital", name:"基因编辑", en:"Genome Editing", year:"2012 年", roots:["dna"],
   tag:"可以定点、精确地改写基因",
   intro:"锌指核酸酶、TALEN 与 CRISPR-Cas9 让基因编辑从随机诱变变成定点修改。作物育种、遗传病治疗与基础研究因此进入快车道，也带来了伦理与监管的新问题。",
   specs:[["出现时间","2012 年（CRISPR-Cas9）"],["关键工具","锌指核酸酶、TALEN、CRISPR-Cas9、碱基编辑"],["关键人物","珍妮弗·杜德纳、埃玛纽埃勒·沙尔庞捷"],["影响","育种、基因治疗、细胞治疗、基础研究"]],
   feats:["把基因编辑的成本与门槛降低了数个数量级","已用于治疗镰状细胞病等遗传性疾病","人类胚胎编辑的伦理边界，随之成为全球性讨论"],
   subject:"an abstract minimalist 3D rendering of a long DNA double helix with a pair of scissors-like protein molecules gripping one segment while a single glowing base pair is being replaced, soft gray background, conceptual visualization, no text"},
  {id:"new-energy", era:"digital", name:"光伏与动力电池", en:"Solar PV & Batteries", year:"2000 年代", roots:["transistor","chemistry","electric-power"],
   tag:"让电力的来源从燃料转向半导体与化学反应",
   intro:"硅太阳能电池把光子直接变成电流，锂电池把电能存进可反复充放的化学结构。当两者的成本下降一个数量级，光伏与电动汽车就从示范项目变成主流商品。",
   specs:[["出现时间","1954 年（硅电池）；1991 年（锂离子电池商用）"],["关键指标","光伏组件与电池的单瓦时成本"],["关键技术","单晶硅、钙钛矿、磷酸铁锂、三元锂"],["影响","电力结构、汽车产业、储能、气候"]],
   feats:["光伏成本在十余年里下降约九成，成为最便宜的发电方式之一","电池成本下降，使电动汽车从政策驱动转为市场驱动","光伏与电池组合，是分布式能源与电网调峰的关键"],
   subject:"a neat arrangement of energy hardware samples — a dark blue monocrystalline silicon solar cell wafer with fine silver grid lines, beside two cylindrical lithium-ion battery cells with brushed metal casings — on a plain light-gray surface, macro photograph, no text, no logos"},
  {id:"mrna", era:"digital", name:"生物医药与 mRNA 疫苗", en:"Biologics & mRNA Vaccines", year:"2020 年", roots:["dna","genome-editing"],
   tag:"把「药」变成一段可以被细胞读懂的指令",
   intro:"单克隆抗体让药物有了精准靶点，mRNA 技术更进一步：不再直接给药，而是把一段指令送进细胞，让身体自己生产所需的蛋白。疫苗的研发周期因此从十年压缩到一年以内。",
   specs:[["出现时间","1975 年（单克隆抗体）；2020 年（mRNA 疫苗获批）"],["关键技术","单克隆抗体、脂质纳米粒递送、mRNA 修饰"],["关键人物","卡里科、魏斯曼"],["影响","疫苗、肿瘤免疫、罕见病、药物研发速度"]],
   feats:["mRNA 疫苗在疫情中于一年内完成从序列到大规模接种","递送系统（脂质纳米粒）是这类药物的关键技术门槛","同一平台可通过更换序列，快速应对新病原或新靶点"],
   subject:"an abstract minimalist 3D rendering of a translucent lipid nanoparticle sphere containing a coiled glowing mRNA strand, with several similar spheres floating nearby, soft gray background, conceptual visualization, no text"},
  {id:"quantum-tech", era:"digital", name:"量子计算与量子通信", en:"Quantum Technology", year:"2019 年", roots:["modern-physics","transistor"],
   tag:"用量子叠加与纠缠，去做经典机器做不到的事",
   intro:"超导与离子阱量子比特让「量子优越性」被实验证明，量子密钥分发则把窃听变成会被物理定律发现的行为。两者都还很早期，却指向完全不同的计算与安全范式。",
   specs:[["出现时间","1980 年代理论；2019 年（量子优越性实验）"],["关键概念","量子比特、叠加、纠缠、退相干、量子纠错"],["关键技术","超导电路、离子阱、光量子、量子密钥分发"],["影响","密码学、材料模拟、优化、药物设计"]],
   feats:["量子算法在特定问题上可获得指数级加速（如大数分解）","量子密钥分发把安全性建立在物理定律之上，而非计算难度","量子纠错与规模化，是从实验室走向实用的最大门槛"],
   subject:"an abstract minimalist 3D rendering of a golden chandelier-like cryostat with concentric tiers of copper plates and fine wiring descending toward a small glowing core, soft gray background, conceptual visualization, no text"},

  /* ==================== 近未来 ==================== */
  {id:"agi", era:"future", name:"通用人工智能", en:"Artificial General Intelligence", year:"目标 2030 年代", roots:["machine-learning"],
   tag:"在几乎所有认知任务上达到或超过人的机器",
   intro:"大模型已经证明「规模 + 数据 + 通用结构」可以得到跨任务的能力。通用人工智能要解决的是推理可靠性、长期规划、自主使用工具与价值对齐问题：它可能带来生产力跃升，也带来治理难题。",
   specs:[["状态","研究中"],["关键挑战","推理可靠性、长期记忆、工具使用、价值对齐、安全治理"],["关键条件","算力、数据、算法、评测体系"],["潜在影响","科研、教育、医疗、劳动结构"]],
   feats:["从专用模型走向通用模型，是人工智能路线的关键转向","「对齐」问题决定能力越强时风险是否可控","一旦实现，可能成为本世纪影响面最广的单一技术"],
   subject:"an abstract minimalist 3D rendering of a luminous sphere made of densely interconnected glowing filaments with a soft halo, floating above a faint reflective surface, soft gray background, conceptual visualization, no text"},
  {id:"fusion", era:"future", name:"可控核聚变", en:"Fusion Power", year:"目标 2030—2050 年代", roots:["modern-physics","nuclear-fission"],
   tag:"用海水里的燃料点亮城市",
   intro:"磁约束托卡马克与激光惯性约束都在追求让氢同位素在亿度高温下持续聚变。燃料几乎取之不尽、产物没有长寿命放射性废料，但稳定点火与耐中子材料仍是长期难题。",
   specs:[["状态","实验中（已实现净能量增益实验）"],["关键技术","磁约束托卡马克、惯性约束、超导磁体、耐中子材料"],["燃料","氘与氚（海水中大量存在）"],["潜在影响","能源结构、气候、地缘格局"]],
   feats:["2022 年惯性约束实验首次实现输出能量超过输入激光能量","氘在海水中的储量极大，燃料约束几乎消失","材料在强中子辐照下的寿命，是商业化最难的工程门槛之一"],
   subject:"an abstract minimalist 3D rendering of a glowing toroidal fusion reactor with a ring of superconducting coils around a luminous ring of plasma, soft gray background, conceptual visualization, no text"},
  {id:"robots", era:"future", name:"通用机器人", en:"General-purpose Robotics", year:"目标 2030 年代", roots:["agi","machine-learning"],
   tag:"让智能拥有可以干活的身体",
   intro:"视觉-语言-动作模型让机器人能理解指令并适应陌生环境，人形平台则试图复用为人类设计的工具与环境。硬件成本、可靠性与安全，是走向规模化的三道门槛。",
   specs:[["状态","样机与早期商用"],["关键技术","具身智能、视觉-语言-动作模型、灵巧手、力控关节"],["关键指标","成本、续航、可靠性、安全性"],["潜在影响","制造、物流、家庭服务、养老"]],
   feats:["具身智能把大模型的常识迁移到物理世界","灵巧操作（抓取、装配）是比行走更难的挑战","与人类共处的安全标准，将决定落地速度"],
   subject:"an abstract minimalist 3D rendering of a sleek white humanoid robot standing upright with segmented arms and visible cylindrical joint actuators, matte surfaces, plain light-gray studio background, three-quarter view, no text, no logos"},
  {id:"brain-computer", era:"future", name:"脑机接口", en:"Brain-Computer Interface", year:"目标 2030 年代", roots:["medical-imaging","machine-learning"],
   tag:"让神经信号与机器直接对话",
   intro:"高密度电极阵列已经能让瘫痪者用意念打字、控制机械臂，也能让失语者重新「说话」。更高带宽、更低创伤与长期稳定的植入体，是下一步的关键。",
   specs:[["状态","临床试验中"],["关键技术","皮层电极阵列、柔性电极、神经解码、无线供电"],["关键指标","通道数、长期稳定性、延迟"],["潜在影响","医疗康复、假肢、人机交互"]],
   feats:["神经解码已在临床帮助瘫痪患者控制光标与机械臂","柔性电极与无线方案，正在降低植入创伤与感染风险","通道数、寿命与生物相容性，是决定能否普及的三个变量"],
   subject:"an abstract minimalist 3D rendering of a small thin flexible electrode array with many fine metallic contact points along a translucent ribbon, curving above a faint spherical surface, soft gray background, conceptual visualization, no text"},
  {id:"synthetic-biology", era:"future", name:"合成生物学", en:"Synthetic Biology", year:"目标 2030 年代", roots:["genome-editing","machine-learning"],
   tag:"把细胞当作可以编程的工厂",
   intro:"把基因线路、启动子与代谢通路当作可组合的标准元件，就能让微生物按设计生产药物、材料与燃料。合成基因组与人工细胞，正在把生物学变成一门工程学科。",
   specs:[["状态","已在部分产品上落地"],["关键技术","基因线路、底盘细胞、代谢工程、人工基因组、无细胞合成"],["关键产物","药物、生物基材料、人造肉、生物燃料"],["潜在影响","化工、医药、农业、材料"]],
   feats:["人工合成胰岛素与青蒿素前体，已实现工业化生物制造","合成酵母基因组，是首次对真核生物基因组的系统重写","与人工智能结合后，蛋白质结构与功能的设计速度大幅提升"],
   subject:"an abstract minimalist 3D rendering of a translucent cell-like capsule containing glowing modular DNA circuits and floating molecular blocks, soft gray background, conceptual visualization, no text"},
  {id:"longevity", era:"future", name:"抗衰老与再生医学", en:"Longevity & Regenerative Medicine", year:"目标 2030—2040 年代", roots:["genome-editing","mrna"],
   tag:"把「衰老」当成可以干预的生物学过程",
   intro:"细胞重编程、衰老细胞清除与干细胞治疗，正在把衰老从宿命变成一组可以被影响的机制。延长健康寿命而非单纯延长寿命，是目前更现实的目标。",
   specs:[["状态","研究中与早期临床"],["关键技术","诱导多能干细胞、细胞重编程、衰老细胞清除、基因治疗、器官再生"],["关键目标","延长健康寿命"],["潜在影响","医疗、养老、劳动结构、伦理"]],
   feats:["诱导多能干细胞证明成熟细胞可以被「重置」，并因此获得诺贝尔奖","小鼠实验中多种干预已显著延长健康期","从动物到人、从指标到结局，仍需要长期而昂贵的验证"],
   subject:"an abstract minimalist 3D rendering of a translucent stem cell dividing into two daughter cells with a glowing inner nucleus, several similar cells floating nearby, soft gray background, conceptual visualization, no text"}
];

/* ============================ 图标 ============================ */
/* 时代图标（占位块用，纯描边 SVG）：与 ERAS[].icon 一一对应。 */
var ICONS = {
  fire:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21c3.3 0 5.6-2.2 5.6-5.3 0-2.3-1.3-3.9-2.6-5.3-1-1-1.7-2-1.7-3.4-2 1.1-3.2 2.6-3.6 4.2-.5-.5-.8-1.1-.9-1.8-1.6 1.5-2.4 3.6-2.4 6.3C6.4 18.8 8.7 21 12 21z"/><path d="M12 21c1.6 0 2.6-1.1 2.6-2.6 0-1.6-1.3-2.2-1.6-3.6-1 .7-1.6 1.6-1.6 2.6 0 .6.3 1 .3 1.6 0 .7-.5 1.2-1.2 1.4"/></svg>',
  pot:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M7 5.6h10c.3 0 .5.2.5.5v1.4H6.5V6.1c0-.3.2-.5.5-.5z"/><path d="M6 9h12c.8 3.2.5 6-1 8.3-1 1.6-2.6 2.4-5 2.4s-4-.8-5-2.4C5.5 15 5.2 12.2 6 9z"/><path d="M9.5 12.5c.8.5 1.7.8 2.5.8"/></svg>',
  column:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M4.5 6h15"/><path d="M6 6l1 12h10l1-12"/><path d="M4 20.5h16"/><path d="M9.5 10.5h5"/><path d="M9.5 14h5"/></svg>',
  castle:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M4 20.5V9l3 1.6V6l3 1.6V4l4 2.2V4l3 2.6V6l3 3v11.5z"/><path d="M10 20.5v-4.6a2 2 0 0 1 4 0v4.6"/></svg>',
  sextant:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3.5 20 8v8l-8 4.5L4 16V8z"/><circle cx="12" cy="11" r="2.6"/><path d="M12 8.4V5.6"/><path d="M14.4 12.6l2.6 2.6"/></svg>',
  gear:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3.2"/><path d="M12 3.4v2.4M12 18.2v2.4M3.4 12h2.4M18.2 12h2.4M6 6l1.7 1.7M16.3 16.3 18 18M18 6l-1.7 1.7M7.7 16.3 6 18"/></svg>',
  bolt:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M13.4 2.6 5.6 13.4h5l-1 8 7.8-10.8h-5z"/></svg>',
  chip:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="6.6" y="6.6" width="10.8" height="10.8" rx="2"/><rect x="10.2" y="10.2" width="3.6" height="3.6" rx="1"/><path d="M9.6 3.4v3.2M14.4 3.4v3.2M9.6 17.4v3.2M14.4 17.4v3.2M3.4 9.6h3.2M3.4 14.4h3.2M17.4 9.6h3.2M17.4 14.4h3.2"/></svg>',
  phone:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="6.8" y="2.6" width="10.4" height="18.8" rx="2.4"/><path d="M10.4 5.4h3.2"/><circle cx="12" cy="18.4" r=".9"/></svg>',
  stars:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3.2l2 4.7 5.1.4-3.9 3.3 1.2 5-4.4-2.7-4.4 2.7 1.2-5L4.9 8.3l5.1-.4z"/><path d="M19 19.4l.8 1.9M20.4 17.6l1.6.5"/></svg>'
};
